import {createHmac,randomBytes} from 'node:crypto';
import {db} from '../db';
import {hashPassword,verifyPassword} from '../../../scripts/password.mjs';
export type AuthUser={id:string;name:string;email:string;role:'ADMIN'|'USER';active:boolean};
export const publicUser={id:true,name:true,email:true,role:true,active:true} as const;
export const sessionAge=7*24*60*60;
export function tokenHash(token:string){const secret=process.env.SESSION_SECRET;if(!secret||secret.length<32||secret.startsWith('replace-with'))throw new Error('SESSION_SECRET must contain at least 32 random characters');return createHmac('sha256',secret).update(token).digest('hex');}
export function credentials(input:unknown,registration=false){if(!input||typeof input!=='object')throw new Error('validation');const v=input as Record<string,unknown>;const email=typeof v.email==='string'?v.email.trim().toLowerCase():'';const password=typeof v.password==='string'?v.password:'';const name=typeof v.name==='string'?v.name.trim():'';if(email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length>128||password.length<(registration?10:1)||registration&&(!name||name.length>80||v.confirmPassword!==password))throw new Error('validation');return {email,password,name};}
export async function registerUser(input:unknown){const {email,password,name}=credentials(input,true);try{return await db.user.create({data:{email,name,passwordHash:await hashPassword(password),role:'USER'},select:publicUser});}catch(e){if((e as {code?:string}).code==='P2002')throw new Error('duplicate');throw e;}}
export async function loginUser(input:unknown){const {email,password}=credentials(input);const user=await db.user.findUnique({where:{email}});const valid=await verifyPassword(password,user?.passwordHash??'scrypt$00000000000000000000000000000000$'+'00'.repeat(64));if(!user||!valid)throw new Error('invalid');if(!user.active)throw new Error('disabled');return {id:user.id,name:user.name,email:user.email,role:user.role,active:user.active};}
export async function createSession(userId:string){const token=randomBytes(32).toString('hex');const expiresAt=new Date(Date.now()+sessionAge*1000);await db.session.create({data:{id:tokenHash(token),userId,expiresAt}});return {token,expiresAt};}
export async function resolveSession(token?:string){if(!token||!/^[a-f0-9]{64}$/.test(token))return null;const session=await db.session.findUnique({where:{id:tokenHash(token)},include:{user:{select:publicUser}}});return session&&session.expiresAt>new Date()&&session.user.active?session.user:null;}
export async function revokeSession(token?:string){if(token)await db.session.deleteMany({where:{id:tokenHash(token)}});}
export async function updateUserActive(actor:AuthUser,id:string,active:boolean){if(actor.role!=='ADMIN')throw new Error('denied');return db.$transaction(async tx=>{const target=await tx.user.findUniqueOrThrow({where:{id}});if(!active&&(actor.id===id||target.role==='ADMIN'&&await tx.user.count({where:{role:'ADMIN',active:true}})<=1))throw new Error('selfLockout');const user=await tx.user.update({where:{id},data:{active},select:publicUser});if(!active)await tx.session.deleteMany({where:{userId:id}});await tx.adminAudit.create({data:{id:randomBytes(16).toString('hex'),entityId:id,operation:'user.active',before:{active:target.active},after:{active},createdBy:actor.id}});return user;});}
