import {accessibleRoutes,supportRoutes} from './routes';
import {appRoutes} from '../navigation';
import type {Intent,ProjectReader,SupportContext,SupportRequest,SupportRole} from './types';
export function classifyIntent(message:string):Intent{
 const text=message.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 if(/admin|question bank|user management|gestion.*utilisateur/.test(text))return 'ADMIN_HELP';
 if(/impact|baseline|compar/.test(text))return 'IMPACT_HELP';
 if(/login|register|log.?out|log in|connexion|se connect|deconnex|inscri|compte|auth|as a user|utilisateur|role/.test(text))return 'AUTH_HELP';
 if(/search|recherch|ctrl|cmd/.test(text))return 'SEARCH_HELP';
 if(/ask nova|support ai|nova support|language|langue/.test(text))return 'FEATURE_HELP';
 if(/^(what is|what does|is |has |who |when |how much|quel|quelle|quand|qui |est-ce|la securite)|inv-\d|sec-\d|acc-\d|approved.*(date|launch)|date.*approuve|project status|etat du projet|budget|facture|invoice/.test(text)&&!/where|ou (sont|trouver|voir)|how (do|does|to)|comment/.test(text))return 'PROJECT_FACT';
 if(/where|ou |open|ouvrir|risk|risque|q0|q10|evidence|preuve|source|document|timeline|chronolog|decision|task|action|tache|overview|accueil/.test(text))return 'NAVIGATION';
 if(/how|comment|feature|fonction|support/.test(text))return 'FEATURE_HELP';
 if(/hello|hi\b|bonjour|salut|help|aide/.test(text))return 'GENERAL_SUPPORT';return 'UNKNOWN';
}
const rolePermissions:Record<SupportRole,string[]>={GUEST:['Normal project tools remain readable for judges. Register/login for an account. No admin access.'],USER:['Dashboard, search, evidence, Ask NOVA, Impact and support. No administration access.'],ADMIN:['All normal tools. Manage custom questions and activate/deactivate users. Roles read-only; no deletion; cannot deactivate self/last active admin. Official questions/evidence/baseline stay protected.']};
export async function buildSupportContext(request:SupportRequest,role:SupportRole,readProject:ProjectReader):Promise<SupportContext>{const intent=classifyIntent(request.message);const page=Object.entries(supportRoutes).find(([,r])=>`/${request.locale}/${appRoutes[r.page]}`.replace(/\/$/,'')===request.currentPath);const words=request.message.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const relevant=accessibleRoutes(role).map(([key,r])=>({key,title:r.title[request.locale],description:r.description[request.locale],score:(key===page?.[0]?2:0)+(words.includes(key.toLowerCase())?4:0)+([r.title.fr,r.title.en].some(title=>title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().split(/[^a-z0-9]+/).some(word=>word.length>=4&&words.includes(word)))?4:0)+([...words.matchAll(/[a-z]{4,}/g)].some(([word])=>r.description[request.locale].toLowerCase().includes(word))?1:0)+(intent==='IMPACT_HELP'&&key==='impact'||intent==='ADMIN_HELP'&&key.startsWith('admin')||intent==='AUTH_HELP'&&['login','register'].includes(key)||intent==='SEARCH_HELP'&&key==='search'||intent==='PROJECT_FACT'&&['askNova','questions','evidence'].includes(key)?6:0)})).sort((a,b)=>b.score-a.score).slice(0,5).map(({key,title,description})=>({key,title,description}));
 const project=intent==='PROJECT_FACT'?await readProject(request):{facts:[],sources:[]};
 return {appContext:{name:'NOVA 360',purpose:'Grounded project intelligence and traceable operational memory, with immutable baseline and reviewed evidence.'},locale:request.locale,currentRoute:request.currentPath,view:request.view,intent,roleContext:{role,permissions:rolePermissions[role]},pageContext:page&&(!page[1].admin||role==='ADMIN')?{key:page[0],title:page[1].title[request.locale],description:page[1].description[request.locale]}:null,relevantRoutes:relevant,featureContext:['Respond in active locale. Global FR/EN switch preserves route/context. Source originals retain original language.','Support helps navigation; Ask NOVA handles detailed factual analysis. Never mutate data or claim to have performed UI/admin actions.','Baseline is sealed original state; Current replays accepted events. Proposals do not approve decisions; delivery does not validate conditions.','Administration is restricted to authenticated ADMIN. Explain role restrictions to USER/GUEST; never recommend inaccessible admin workflows.'],relevantProjectFacts:project.facts.slice(0,6).map(f=>({...f,summary:f.summary.slice(0,900),title:f.title.slice(0,160)})),sources:project.sources.slice(0,6)};
}
