import type {SupportProvider} from './types';
export const mockSupport:SupportProvider=(message,locale,admin=false)=>{const en=locale==='en';const text=message.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const intents:[RegExp,string,string,string,string][]=[
[/baseline|current|compar|impact/,'impact','Mode Impact','Impact Mode','Comparez Baseline et Actuel dans la barre du projet, puis ouvrez Impact pour examiner les changements.'],
[/admin|question bank|banque/,'admin','Question Bank (Admin)','Question Bank (Admin)','La gestion des questions est réservée aux administrateurs connectés. Les Q01–Q10 restent protégées.'],
[/register|registr|compte|inscri/,'register','Créer un compte','Register','Créez un compte avec votre nom, courriel et un mot de passe de dix caractères minimum. Le rôle initial est USER.'],
[/login|log in|connexion|connect/,'login','Connexion','Login','Connectez-vous depuis le bouton Connexion dans l’en-tête.'],
[/language|langue|fr\/en|anglais|english|french/,'','Vue d’ensemble','Overview','Utilisez le sélecteur FR / EN global dans l’en-tête.'],
[/search|recherch|chercher/,'search','Recherche','Search','Utilisez la recherche en haut de page ou Ctrl/Cmd K, puis filtrez les résultats. Ask NOVA répond aux questions factuelles du projet.'],
[/q0|q10|questions|reponses/,'questions','Q01–Q10','Q01–Q10','Les réponses Q01–Q10 sont accessibles depuis le menu, avec leurs preuves précises.'],
[/risk|risque/,'project/contradictions','Risques','Risks','Consultez les risques et contradictions depuis le menu Risques.'],
[/timeline|chronolog/,'project/timeline','Chronologie','Timeline','La chronologie conserve les événements du projet et les mises à jour reçues.'],
[/decision/,'project/decisions','Décisions','Decisions','Ouvrez Décisions pour consulter les décisions et leurs sources.'],
[/task|action|tache/,'actions','Tâches','Tasks','Les tâches distinguent les engagements documentés des recommandations.'],
[/evidence|preuve|source|invoice|facture/,'evidence','Preuves traçables','Traceable Evidence','Ouvrez Preuves traçables et recherchez la source. Chaque preuve conserve son repère précis. Pour INV-003, recherchez aussi cet identifiant.'],
[/document/,'evidence','Documents','Documents','Les documents originaux sont consultables dans l’explorateur de preuves.'],
[/team|equipe|responsable/,'team','Équipe','Team','La page Équipe présente les responsables documentés.'],
[/overview|ensemble|accueil|dashboard/,'','Vue d’ensemble','Overview','La vue d’ensemble présente les indicateurs, actions, chronologie et sources.']];
const english:Record<string,string>={'impact':'Use Baseline and Current in the project bar, then open Impact to review changes.','admin':'Question management requires a signed-in administrator. Q01–Q10 remain protected.','register':'Register with your name, email and a password of at least ten characters. Your initial role is USER.','login':'Use Login in the header to sign in.','':'Use the global FR / EN selector in the header.','search':'Use the search at the top or Ctrl/Cmd K, then filter results. Ask NOVA answers factual project questions.','questions':'Open Q01–Q10 from the sidebar to see verified answers and precise evidence.','project/contradictions':'Open Risks to review documented risks and contradictions.','project/timeline':'The timeline preserves project events and received updates.','project/decisions':'Open Decisions to see decisions and their sources.','actions':'Tasks distinguish documented commitments from recommendations.','evidence':'Open Traceable Evidence and search for a source. Each citation retains its precise locator. For INV-003, search that identifier too.','team':'Team shows the documented responsible people.'};
const intent=intents.find(([pattern])=>pattern.test(text));if(!intent)return {reply:en?'I help you navigate NOVA 360. Try risks, Q01–Q10, evidence or Impact. Use Ask NOVA for factual project answers.':'Je vous aide à naviguer dans NOVA 360. Essayez risques, Q01–Q10, preuves ou Impact. Utilisez Ask NOVA pour les réponses factuelles.'};const [,route,frLabel,enLabel,frReply]=intent;const target=route==='admin'&&!admin?'login':route;return {reply:en?(route===''&&intent[0].source.includes('overview')?'Overview shows project indicators, actions, timeline and sources.':english[route]):frReply,suggestedActions:[{label:en?'Open '+(target==='login'?'Login':enLabel):'Ouvrir '+(target==='login'?'Connexion':frLabel),href:`/${locale}/${target}`}]};};

