// Reviewed English presentation overlays. IDs, relations and French evidence stay canonical.
export const questions=[
['What is the approved production launch date, and what is the reservation?','October 22, 2026, subject to the three go-live conditions.','Security validation of SEC-210, closure of ACC-303, and approval of the runbook including rollback. The date is approved; launch is not guaranteed.'],
['Why did the date change, and what is the current state of the original cause?','The internal connector delay caused the postponement; INT-101 has been validated and closed since September 17.','Secret rotation and token renewal logic were corrected; 120/120 searches passed. Resolution does not restore October 15. Risk R-01 retains an outdated follow-up.'],
['Who approved the change, and when?','The steering committee on September 10, 2026; Élodie Caron announced approval at 15:25.','Julien Moreau / Boréal proposed October 22 on September 8 at 11:16. The committee approved after the motion at 15:22 and no objections; Nicolas agreed at 15:24. A proposal is not approval.'],
['Who is responsible for the project, and since when?','Nicolas Perron, officially since September 16, 2026.','He succeeds Élodie Caron. Her availability during the handover does not retain her former project-owner role.'],
['What is the authorized contract amount, and how is it calculated?','$204,000 CAD before tax = $180,000 initial contract + $24,000 approved CR-01.','The project committee approved CR-01 on August 14. Exclude the $18,000 CR-04 draft, deferred to phase 2. Authorized, invoiced and paid amounts are distinct.'],
['What is wrong with INV-003, and what treatment should be considered?','INV-003 includes $18,000 for unapproved CR-04; the full $54,000 invoice remains under review.','$36,000 is milestone 3; $18,000 is mobile optimization. Finance requests approval before release. NOVA 360 recommendation: dispute/isolate the line and request a corrected invoice or credit, then validate the balance. No payment or issued credit is established.'],
['Where must production data be hosted, and what confirms implementation?','In Canada, in Canada Central. Migration was reported complete on August 26 and verified by the architecture team at the August 27 committee.','ADR-007, accepted July 23, replaces East US. The v2 diagram, migration email with deployment/connectivity tests, and architecture verification establish implementation. The attached diagram and separate PDF are the same evidence.'],
['Has security been accepted?','No: SEC-210 remains IN VALIDATION; security acceptance has not been given.','The fix was delivered to the validation environment on September 19 and supplier tests passed. Sophie requires her own retest and maintains the status on September 26. EXPORT_CSV is incomplete (object/result missing), rather than entirely absent.'],
['Is accessibility complete, and what remains?','No: ACC-303 is open; the modal Save button cannot be reached using the keyboard.','ACC-301 labels were validated August 15 and ACC-302 contrast August 20; both are closed and their screenshots are historical. ACC-303 reproduces in Chrome/Edge; the focusable-element list is incomplete. A fix is only announced for a future build.'],
['What are the three go-live conditions, and what runbook work is missing?','1. Security validation of SEC-210. 2. Closure of ACC-303. 3. Approval of the runbook including rollback.','September 25 screenshot: step 4 “Rollback procedure” is TODO; step 5 “Post-deployment functional validation” is incomplete. The final runbook was still not received September 29. Sophie, Mélissa and Olivier own the validations; exact dates remain to be confirmed, before go-live.']
];
const uncertainties={Q06:'Final accounting treatment and payment of the balance are not documented.',Q08:'Retest date and final acceptance remain to be confirmed.',Q09:'ACC-303 delivery and validation dates remain to be confirmed.',Q10:'Exact deadlines and operations approval date remain to be confirmed.'};
const factValues=[
'October 15, 2026','October 22, 2026 — conditional','Postpone to October 22','Expired secret and token renewal; insufficient stabilization margin','Validated and closed — 120/120 searches passed','Nicolas Perron since September 16, 2026','Élodie Caron','$204,000 CAD before tax','$24,000 — advanced reports and summary export','$18,000 estimated, not approved; advanced optimization in phase 2','$54,000 under review, including $18,000 CR-04 without approval','Canada Central — Canada','East US','Delivered to validation environment on September 19','SEC-210 validated; ACC-303 closed; runbook approved including rollback','Not accepted — security retest required','Validated with NVDA/VoiceOver; ticket closed','Validated at 5.3:1; ticket closed','Open — modal Save button unreachable by keyboard','Incomplete: rollback + post-deployment functional validation','$132,000 = $60,000 + $72,000','$186,000 = $60,000 + $72,000 + $54,000 (includes $18,000 unauthorized)','Idempotency corrected; 15,000 events replayed without duplicates; closed','620 ms average over 50 trials; closed','SSO, requests, attachments, workflow, tracking dashboard, standard reports + CR-01 advanced reports'];
const words={
'Échéancier':'Schedule','Intégration':'Integration','Gouvernance':'Governance','Finances':'Finance','Portée':'Scope','Architecture':'Architecture','Sécurité':'Security','Accessibilité':'Accessibility','Exploitation':'Operations','Données':'Data','Performance':'Performance','Go-live':'Go-live',
'date cible':'target date','date approuvée':'approved date','propose':'proposes','cause du retard':'cause of delay','état':'state','responsable':'project owner','responsable initiale':'initial project owner','plafond autorisé':'authorized ceiling','montant approuvé':'approved amount','hébergement':'hosting','région initiale':'initial region','correctif':'fix','go-live':'go-live','acceptation':'acceptance','labels':'labels','contraste':'contrast','clavier':'keyboard','runbook':'runbook','payé':'paid','facturé':'invoiced','migration':'migration','performance':'performance','portée phase 1':'phase 1 scope','Données production':'Production data',
'Cause':'Cause','Proposition':'Proposal','Discussion':'Discussion','Approbation':'Approval','Mise en œuvre':'Implementation','Validation':'Validation','Décision de portée':'Scope decision','Approbation financière':'Financial approval'};
const actions=[
['Retest and accept SEC-210','Replay the export scenario; verify object and result; document security acceptance.'],
['Fix and validate ACC-303','Correct the focusable-element list; reach Save by keyboard in Chrome/Edge; Mélissa confirms closure.'],
['Complete and approve the runbook','Provide executable rollback and post-deployment functional validation; obtain operations approval.'],
['Address the CR-04 line in INV-003','Obtain the justification requested by Finance; do not release CR-04 spending without approval.'],
['Request a corrected invoice or credit','Isolate/dispute the unapproved $18,000; validate the $36,000 balance. The corpus does not yet specify the accounting mechanism.'],
['Correct plans and communications','Replace October 15 with conditional October 22 in the plans.'],
['Update R-01 in the risk register','Retain the delay history but reflect September 17 INT-101 validation.']];
const decisions=[
['Production launch postponed','Connector delay, stabilization and testing without compression.','Plan v3 not corrected; communications clarified','Three conditions still open',['Internal connector delay','September 8, 11:16 — Julien recommends October 22','September 10 — stabilization, testing and operations','September 10, 15:25 — committee / Élodie','Communications clarified; plan v3 still says October 15','Go-live remains conditional; no final authorization']],
['Data in Canada — ADR-007','Production data must remain in Canada.','Migration complete','Architecture verified August 27',['Initial architecture: East US','July 23 — ADR-007 accepted','August 26 — migration and connectivity test','August 27 — architecture team verifies']],
['CR-01 — advanced reports','Add advanced reports and summary export.','Invoiced in INV-002','Technical acceptance is not established by these documents',['August 14 — $24,000 authorized','Invoiced and paid in INV-002; technical validation to confirm']],
['CR-04 — advanced mobile deferred','Outside approved phase 1; deferred to phase 2 on September 24.','Spending not approved','Not applicable — no approved financial commitment',['September 4 — $18,000 estimate, draft','September 24 — deferred to phase 2; no spending authorized','Not documented; CR-04 remains unapproved']]];
const timeline=[
['NOVA launched','Élodie; October 15 target; $180,000; phase 1.'],['Canada Central selected','ADR-007 replaces East US.'],['CR-01 approved','Additional $24,000; $204,000 ceiling.'],['Labels validated','ACC-301 closed after retest.'],['Contrast validated','ACC-302 closed; ratio 5.3:1.'],['Canada Central migration','Migration complete and connectivity tested.'],['Architecture verified','Architecture team confirms migration.'],['INT-101 threatens the schedule','401 errors and token renewal; stabilization margin.'],['Performance restored','620 ms over 50 trials; PERF-501 closed.'],['October 22 postponement proposed','Julien requests governance decision.'],['DATA-401 closed','15,000 events replayed without duplicates.'],['October 22 officially approved','Élodie announces committee approval; criteria retained.'],['Nicolas takes over NOVA','Official transition from Élodie.'],['INT-101 validated and closed','120/120; Marc confirms. Postponement stays in effect.'],['SEC-210 delivered for validation','Supplier tests pass; Sophie’s retest still required.'],['INV-003 needs clarification','Finance requests approval for $18,000 CR-04.'],['Advanced mobile in phase 2','CR-04 unapproved; no spending authorized.'],['Three go-live conditions','Security, ACC-303 keyboard access, approved runbook.'],['Final runbook not received','Rollback and post-deployment validation are missing.']];
const contradictions=[
['Plan v3: October 15 or 22?','September 12 plan v3 — E7/F7: October 15','September 10 committee — October 22 approved','Formal committee approval takes precedence over an outdated cell. September 15 Teams confirms the plan was not corrected. Keep October 15 as historical.'],
['R-01: connector still open?','Register named September 29 — R-01 Open; September 9 follow-up','INT-101 — validated and closed September 17','Marc’s validation and 120/120 searches take precedence over the September 9 follow-up copied into the register. Closing the issue does not change the approved date.'],
['Security green or acceptance pending?','September 21 report: GREEN, fix delivered','Sophie September 26: IN VALIDATION, acceptance not given','The report summarizes delivery, not acceptance. The ticket and committee establish security validation status; acceptance remains required.'],
['Accessibility complete or ACC-303 open?','September 21 report: GREEN, fixes applied','ACC-303 and September 26 committee: Save unreachable by keyboard','Labels and contrast are validated; that does not close a separate keyboard scenario. Mélissa’s comment and the committee confirm the current blocker.'],
['East US or Canada Central?','Architecture v1: East US','ADR-007 and migration: Canada Central','The accepted ADR explicitly supersedes v1; migration was tested and verified. Attachments are not additional independent confirmation.'],
['CR-04 invoiced but authorized?','INV-003 includes $18,000 advanced mobile','CR-04 draft; scope decision prohibits unapproved spending','An invoice does not authorize expenditure. Exclude CR-04 from the authorized ceiling; address the line with Finance.']];
const summaries=[
'Élodie, $180,000, October 15 target and initial scope.','Initial charter and phase 1 scope.','Julien proposes October 22; governance decision awaited.','Élodie moves postponement; approval at 15:25; criteria retained.','Connector delay; stabilization, integrated tests and margin for defects.','Three conditions: SEC-210, ACC-303, runbook including rollback.','October 22 approved but conditional, no guaranteed launch.','Secret and token renewal corrected; 120/120; Marc validates and closes.','Marc confirms 120/120 and INT-101 closure.','Nicolas officially takes over from September 16.','September 16 handover and points requiring attention.','Initial maximum $180,000 CAD; written approved change required.','$24,000 approved August 14 by project committee.','$18,000 estimated; draft, approval required.','INV-001 paid: $60,000.','INV-002 paid: $48,000 + $24,000 = $72,000.','$36,000 milestone 3 + $18,000 mobile = $54,000, under review.','Amélie requests CR-04 approval before release.','Advanced mobile deferred to phase 2; no spending without approval.','Nicolas excludes CR-04 from phase 1 and prohibits unapproved invoicing.','Accepted July 23 decision: Canada Central; v1 superseded.','US region in initial architecture.','Diagram revised after ADR-007.','Migration complete; deployment and connectivity tested.','Architecture team verified migration at August 27 committee.','Fix delivered for validation; supplier tests pass, retest requested.','EXPORT_CSV exists but object/result missing; security maintains IN VALIDATION.','Both columns show ---; export recorded but incomplete.','Programmatic label fixed, validated with NVDA/VoiceOver; closed.','Contrast corrected, retest 5.3:1; closed.','Focus stuck between Name and Comment; Save unreachable; still open.','Keyboard focus cannot reach Save (build 2026.09.17).','Rollback missing; final runbook still not received September 29.','4. Rollback procedure: TODO. 5. Post-deployment functional validation: incomplete.','September 12 plan v3 retains October 15 despite approval.','Nicolas confirms September 10 committee; plan not corrected.','R-01 retains old state despite September 29 filename.','GREEN based on delivered fixes; prepared before detailed verification.','Idempotency fixed; 15,000 events replayed without duplicates; closed.','Index/query fixed; average 620 ms over 50 trials; closed.'];
const roles=['Project manager since September 16','Initial project manager; handover','Boréal Numérique supplier','Architecture / integration','Security validation','Accessibility validation','Operations approval','Finance','Data migration','Status communications'];
function translateNamed(value){return typeof value==='string'?(words[value]??value.replaceAll(' (correctif)',' (fix)').replaceAll(' (rédaction)',' (drafting)').replaceAll(' (approbation)',' (approval)').replaceAll('Comité de direction; Élodie Caron prononce l’approbation','Steering committee; Élodie Caron announces approval').replaceAll('Comité de projet','Project committee').replaceAll('Atelier architecture / ADR accepté','Architecture workshop / accepted ADR')):value;}
export function englishOverlay(kind,data,index){
 const common={};for(const key of ['topic','subject','predicate','owner','approvedBy'])if(data[key])common[key]=translateNamed(data[key]);
 if(kind==='questions')return {...common,question:questions[index][0],answer:questions[index][1],nuance:questions[index][2],uncertainty:uncertainties[data.id]??'No uncertainty in this answer; established at baseline.',confidenceReason:'Direct evidence and precise locators reviewed; authority, delivery and validation distinguished.',crossSourceConfirmation:'Distinct sources; MIME attachments and archive copies excluded from independent corroboration.'};
 if(kind==='facts')return {...common,value:factValues[index],baselineValue:factValues[index],authority:'Explicit authority in the content; see evidence',confidenceReason:'Direct passage verified; state explained by the sources.'};
 if(kind==='actions')return {...common,title:actions[index][0],description:actions[index][1],deadlineConstraint:data.relatedGoLiveCondition?'Before go-live':'To confirm'};
 if(kind==='decisions'){const a=decisions[index];return {...common,title:a[0],rationale:a[1],implementationState:a[2],validationState:a[3],phases:data.phases.map((p,i)=>({...p,label:translateNamed(p.label),text:a[4][i]}))};}
 if(kind==='timeline')return {title:timeline[index][0],description:timeline[index][1]};
 if(kind==='contradictions'){const a=contradictions[index];return {topic:a[0],factA:a[1],factB:a[2],resolution:a[3],authorityReason:a[3],resolutionBasis:'Authority and date of facts, not the filename.',dateReason:'See evidence dates and precise locators.'};}
 if(kind==='citations')return {excerptSummary:summaries[index]};
 if(kind==='people')return {role:roles[index]};
 if(kind==='conditions')return {title:['Security acceptance SEC-210','Accessibility closure ACC-303','Runbook + rollback approval'][index]};
 return {};
}
