import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile,unlink} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import path from 'node:path';
async function run(){const file=path.resolve('data/runtime/auth-test.db');await mkdir(path.dirname(file),{recursive:true});await unlink(file).catch(e=>{if(e.code!=='ENOENT')throw e;});const sql=new DatabaseSync(file);for(const migration of ['202610030001_initial','202610040001_auth'])sql.exec(await readFile(`prisma/migrations/${migration}/migration.sql`,'utf8'));sql.close();process.env.NOVA_DATABASE_URL='file:'+file.replaceAll('\\','/');process.env.SESSION_SECRET='test-only-session-secret-32-characters-long';process.env.ADMIN_EMAIL='seed@nova.test';process.env.ADMIN_PASSWORD='Test-only-password-2026';const {db}=await import('../src/lib/db');const auth=await import('../src/lib/auth/service');const {seed,db:seedDb}=await import('../scripts/db-seed.mjs');after(async()=>{await db.$disconnect();await seedDb.$disconnect();});
test('registration validates, normalizes unique email, hashes password and ignores requested ADMIN role',async()=>{const input={name:'Test User',email:' User@nova.test ',password:'Valid-password-2026',confirmPassword:'Valid-password-2026',role:'ADMIN'};const user=await auth.registerUser(input);assert.equal(user.role,'USER');assert.equal(user.email,'user@nova.test');const stored=await db.user.findUniqueOrThrow({where:{id:user.id}});assert.ok(stored.passwordHash.startsWith('scrypt$'));assert.ok(!stored.passwordHash.includes(input.password));await assert.rejects(auth.registerUser(input),/duplicate/);await assert.rejects(auth.registerUser({...input,email:'bad'}),/validation/);await assert.rejects(auth.registerUser({...input,confirmPassword:'mismatch'}),/validation/);});
test('login accepts correct password and rejects incorrect, nonexistent and inactive accounts',async()=>{assert.equal((await auth.loginUser({email:'user@nova.test',password:'Valid-password-2026'})).role,'USER');await assert.rejects(auth.loginUser({email:'user@nova.test',password:'wrong'}),/invalid/);await assert.rejects(auth.loginUser({email:'missing@nova.test',password:'wrong'}),/invalid/);await db.user.update({where:{email:'user@nova.test'},data:{active:false}});await assert.rejects(auth.loginUser({email:'user@nova.test',password:'Valid-password-2026'}),/disabled/);await db.user.update({where:{email:'user@nova.test'},data:{active:true}});});
test('opaque DB sessions expire and logout revokes token',async()=>{const user=await db.user.findUniqueOrThrow({where:{email:'user@nova.test'}});const s=await auth.createSession(user.id);assert.equal((await auth.resolveSession(s.token))?.id,user.id);assert.ok(!await db.session.findUnique({where:{id:s.token}}));await auth.revokeSession(s.token);assert.equal(await auth.resolveSession(s.token),null);const expired=await auth.createSession(user.id);await db.session.update({where:{id:auth.tokenHash(expired.token)},data:{expiresAt:new Date(0)}});assert.equal(await auth.resolveSession(expired.token),null);assert.equal(await auth.resolveSession(),null);});
test('seed creates one admin, preserves users and denies self-lockout and USER management',async()=>{await seed();await seed();const admin=await db.user.findUniqueOrThrow({where:{email:'seed@nova.test'}});assert.equal(admin.role,'ADMIN');assert.equal(await db.user.count({where:{role:'ADMIN'}}),1);assert.equal(await db.user.count(),2);await assert.rejects(auth.updateUserActive(admin,admin.id,false),/selfLockout/);const user=await db.user.findUniqueOrThrow({where:{email:'user@nova.test'}});await assert.rejects(auth.updateUserActive(user,admin.id,false),/denied/);const session=await auth.createSession(user.id);await auth.updateUserActive(admin,user.id,false);assert.equal(await auth.resolveSession(session.token),null);});
}
void run().catch(e=>{console.error(e);process.exitCode=1;});
