'use client';
import {useEffect,useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {useRouter,usePathname,useSearchParams} from 'next/navigation';
import {Search,Menu,X,LockKeyhole,GitCompareArrows} from 'lucide-react';
import {useProject} from '@/lib/project-context';
import type {ProjectEvent} from '@/lib/impact';
import type {SearchResult} from '@/lib/repositories/search';
import {Overview} from './overview';
import {TimelinePage,NewEventsTimeline,DecisionsPage,ActionsPage,ContradictionsPage,QuestionsPage} from './project-pages';
import {EvidenceExplorer,EvidenceModal} from './evidence';
import {ImpactPage} from './impact-page';
import {AskPage} from './ask-page';
import {Brief} from './brief';
import {HomePage} from './home';
import {SearchExperience,SearchPalette} from './search';
import type {AuthUser} from '@/lib/auth/service';
import {SupportChat} from './support-chat';
import {DocumentsPage} from './documents-page';
import {UsersPage} from './users-page';
import {AdminPage} from './admin';
import {appRoutes as route} from '@/lib/navigation';
export function Hub({initialPage,user}:{initialPage:string;user:AuthUser|null}){
 const a=useTranslations('auth');const d=useTranslations('dashboard');const t=useTranslations('nav');const locale=useLocale();const router=useRouter();const pathname=usePathname();const params=useSearchParams();const {baseline,canonicalBaseline,deriveCurrent,displayFacts,isProjectEvent}=useProject();const page=route[initialPage]!==undefined?initialPage:'home';
 const [headerQuery,setHeaderQuery]=useState('');const [legacy,setLegacy]=useState<ProjectEvent[]>([]);const [citation,setCitation]=useState<string|null>(null);const [events,setEvents]=useState<ProjectEvent[]>([]);const [loaded,setLoaded]=useState(false);const [view,setView]=useState(params.get('view')==='baseline'?'baseline':'current');const [mobile,setMobile]=useState(false);const [notice,setNotice]=useState('');const [searchOpen,setSearchOpen]=useState(false);
 useEffect(()=>{const abort=new AbortController();fetch('/api/events',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{setEvents(data);setLoaded(true);try{const raw=localStorage.getItem('nova360.events.v1');if(raw){const previous=JSON.parse(raw);if(!Array.isArray(previous)||previous.length>200||!previous.every(isProjectEvent))throw new Error('legacy');if(previous.some((e:ProjectEvent)=>!data.some((current:ProjectEvent)=>current.id===e.id)))setLegacy(previous);}}catch{setNotice(t('legacyError'));}}).catch(()=>{if(!abort.signal.aborted){setNotice(t('loadingError'));setView('baseline');}});return ()=>abort.abort();},[t,isProjectEvent]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setSearchOpen(open=>!open);}};window.addEventListener('keydown',handler);return ()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('citation'))setTimeout(()=>setCitation(params.get('citation')),0);},[pathname]);
 const current=useMemo(()=>deriveCurrent(events),[deriveCurrent,events]);const facts=displayFacts(view==='baseline'?canonicalBaseline.facts:current);
 const navigate=(next:string,params?:Record<string,string>,anchor?:string)=>{setMobile(false);const nextQuery=new URLSearchParams(params);if(view==='baseline')nextQuery.set('view','baseline');const query=nextQuery.toString();router.push('/'+locale+'/'+(route[next]??'')+(query?'?'+query:'')+(anchor?'#'+anchor:''));};
 const persist=async(incoming:ProjectEvent[])=>{try{const response=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:incoming,locale})});if(!response.ok)throw new Error();setEvents(await response.json());setLoaded(true);return true;}catch{setNotice(t('eventError'));return false;}};
 const openResult=(result:SearchResult)=>{if(result.citationId){setCitation(result.citationId);return;}navigate(result.page,result.sourceId?{source:result.sourceId}:undefined,result.anchor);};
 const changeView=(next:string)=>{setView(next);const query=new URLSearchParams(params.toString());if(next==='baseline')query.set('view',next);else query.delete('view');router.replace(pathname+(query.size?'?'+query.toString():''),{scroll:false});};
 const closeEvidence=()=>{setCitation(null);if(params.has('citation')){const query=new URLSearchParams(params.toString());query.delete('citation');router.replace(pathname+(query.size?'?'+query.toString():''),{scroll:false});}};
 const switchLocale=(next:string)=>{const query=new URLSearchParams(window.location.search);if(view==='baseline')query.set('view','baseline');else query.delete('view');if(citation)query.set('citation',citation);router.push(pathname.replace(/^\/(fr|en)(?=\/|$)/,'/'+next)+(query.size?'?'+query.toString():'')+window.location.hash);};
 const sidebar=['home','timeline','questions','decisions','actions','contradictions','evidence',...(user?.role==='ADMIN'?['admin','users']:[]),'documents','team'];
 return <div className="nova-app"><a className="skip-link" href="#main">{t('skip')}</a><header className="enterprise-header"><div className="institution-bar"><strong>Loto-Québec</strong><span>{t('projectLabel')}</span><div className="language-switch" aria-label={t('language')}>{['fr','en'].map(lang=><button key={lang} lang={lang} aria-pressed={locale===lang} onClick={()=>switchLocale(lang)}>{lang.toUpperCase()}</button>)}</div></div><div className="product-bar"><button className="product-brand" onClick={()=>navigate('home')}>NOVA <span>360</span><small>PROJECT INTELLIGENCE HUB</small></button><button className="menu-toggle icon-button" aria-label={mobile?t('close'):t('menu')} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><form className="header-search" onSubmit={e=>{e.preventDefault();if(headerQuery.trim())navigate('ask',{q:headerQuery.trim()});}}><Search size={18}/><input aria-label={d('search')} placeholder={d('search')} value={headerQuery} maxLength={1000} onChange={e=>setHeaderQuery(e.target.value)}/><button type="button" className="icon-button" aria-label={t('search')} onClick={()=>setSearchOpen(true)}><Search size={18}/></button></form><div className="header-account">{user?<details><summary><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span>{user.name} · {user.role}</summary><div><strong>{a('account')}</strong><p>{user.email}</p><button className="text-button" onClick={async()=>{const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok){router.push('/'+locale);router.refresh();}else setNotice(a('unavailable'));}}>{a('logout')}</button></div></details>:<><a href={'/'+locale+'/login'}>{a('login')}</a><a href={'/'+locale+'/register'}>{a('register')}</a></>}</div></div></header>
 <div className="project-context-bar"><div><LockKeyhole size={14}/><span>{t('baseline')} · {new Intl.DateTimeFormat(locale==='en'?'en-CA':'fr-CA',{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'America/Montreal'}).format(new Date(baseline.asOf))}</span></div><div className="state-toggle"><button aria-pressed={view==='baseline'} className={view==='baseline'?'active':''} onClick={()=>changeView('baseline')}>{t('baselineView')}</button><button aria-pressed={view==='current'} className={view==='current'?'active':''} onClick={()=>changeView('current')}>{t('current')}{events.length>0&&<span>{events.length}</span>}</button><button aria-label={t('compare')} onClick={()=>navigate('impact')}><GitCompareArrows size={17}/></button></div></div>
 <div className="dashboard-layout"><nav className={mobile?'dashboard-sidebar open':'dashboard-sidebar'} aria-label={t('primary')}><button className="drawer-close" aria-label={t('close')} onClick={()=>setMobile(false)}><X size={18}/>{t('close')}</button>{sidebar.map(id=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}>{id==='evidence'?d('evidence'):id==='questions'?'Q01–Q10':id==='users'?a('users'):id==='admin'?d('questionBank'):id==='home'?d('title'):id==='contradictions'?d('risks'):id==='documents'?d('documents'):id==='team'?d('team'):t(id)}</button>)}{['impact','ask','brief'].map(id=><button key={id} onClick={()=>navigate(id)}>{t(id)}</button>)}</nav>
 <main id="main" tabIndex={-1} className="enterprise-main">{!loaded&&view==='current'&&<p role="status" className="notice">{t('loading')}</p>}{legacy.length>0&&<div className="notice">{t('legacy')}<button className="text-button" onClick={async()=>{if(await persist(legacy))setLegacy([]);}}>{t('importLegacy')}</button></div>}{notice&&<div className="notice" role="alert">{notice}<button className="text-button" onClick={()=>setNotice('')}>{t('close')}</button></div>}{view==='baseline'&&events.length>0&&<div className="notice">{t('baselineNotice')}</div>}
 {page==='home'&&<HomePage facts={facts} onNavigate={navigate} onEvidence={setCitation}/>}{page==='overview'&&<Overview facts={facts} onEvidence={setCitation} onNavigate={navigate}/>}{page==='timeline'&&<><TimelinePage onEvidence={setCitation}/><NewEventsTimeline events={view==='baseline'?[]:events} onEvidence={setCitation}/></>}{page==='decisions'&&<DecisionsPage onEvidence={setCitation}/>}{page==='actions'&&<ActionsPage facts={facts} onEvidence={setCitation}/>}{page==='contradictions'&&<ContradictionsPage onEvidence={setCitation} facts={facts}/>}{page==='evidence'&&<EvidenceExplorer onEvidence={setCitation}/>}{page==='documents'&&<DocumentsPage/>}{page==='questions'&&<QuestionsPage facts={facts} onEvidence={setCitation}/>}{page==='ask'&&<AskPage key={params.get('q')??''} facts={facts} onEvidence={setCitation} onNavigate={navigate}/>}{page==='impact'&&loaded&&<ImpactPage events={events} facts={current} onAppend={event=>persist([event])} onImport={persist} onEvidence={setCitation}/>}{page==='brief'&&<Brief facts={facts}/>}{page==='search'&&<SearchExperience onOpen={openResult}/>}{page==='admin'&&user?.role==='ADMIN'&&<div className="admin-content"><AdminPage onSaved={()=>router.refresh()}/></div>}{page==='users'&&user?.role==='ADMIN'&&<UsersPage/>}{page==='team'&&<TeamPage/>}
 <footer className="app-footer"><span>NOVA 360 · Project Intelligence Hub</span><span>{t('footer')}</span></footer></main></div><EvidenceModal view={view} citationId={citation} onClose={closeEvidence} onEvidence={setCitation} events={events}/><SupportChat key={locale} view={view==='baseline'?'baseline':'current'}/><SearchPalette open={searchOpen} onClose={()=>setSearchOpen(false)} onOpen={openResult}/></div>;
}

function TeamPage(){const t=useTranslations('dashboard');const {people}=useProject();return <section><h1>{t('team')}</h1><div className="priority-grid">{people.map(p=><article className="card" key={p.id}><h2>{p.name}</h2></article>)}</div></section>;}
