'use client';
import type {DerivedFact} from '@/lib/impact';
import {useTranslations} from 'next-intl';
import {useProject} from '@/lib/project-context';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, CircleAlert, FileCheck2, ShieldCheck, UserRound, Wallet, Printer } from 'lucide-react';


import { Badge, FactValue, EvidenceLinks, type EvidenceHandler } from './primitives';
export function Overview({facts,onEvidence,onNavigate}: {facts:DerivedFact[];onEvidence:EvidenceHandler;onNavigate:(page:string)=>void}) {
 const t=useTranslations('ui');const {baseline,factById,formatMoney}=useProject();

  const find=(id:string)=>facts.find(f=>f.id===id);
  const approved=baseline.conditions.filter(c=>find(c.factId)?.informationState==='validated').length;
  return <>
  <div className="overview-intro"><div><span className="eyebrow">{t('text005')}</span><h1>{t('text006')}<br/><span>{t('text007')}</span></h1><p>{t('text008')}<br className="desktop-break"/>{t('text009')}</p><div className="intro-buttons"><button className="button primary" onClick={()=>onNavigate('questions')}>{t('text010')}<ArrowRight size={16}/></button><button className="button secondary" onClick={()=>onNavigate('brief')}><Printer size={16}/>{t('text011')}</button></div></div><div className="readiness-orbit"><div className="orbit-ring"><div><span className="eyebrow">{t('text012')}</span><strong>{approved}<span>{t('text013')}</span></strong><span className="orbit-status">{approved===3?t('text014'):t('text015')}</span></div></div><span className="orbit-footnote">{t('text016')}</span></div></div>
  <div className="kpi-grid"><article className="card kpi"><span className="kpi-label"><CalendarDays size={17}/>{t('text017')}</span><FactValue fact={find('FACT-002')} onEvidence={onEvidence}/><p>{t('text018')}</p></article><article className="card kpi"><span className="kpi-label"><UserRound size={17}/>{t('text019')}</span><FactValue fact={find('FACT-006')} onEvidence={onEvidence}/><p>{t('text020')}</p></article><article className="card kpi"><span className="kpi-label"><Wallet size={17}/>{t('text021')}</span><FactValue fact={find('FACT-008')} onEvidence={onEvidence}/><p>{t('text022')}</p></article><article className="card kpi warning-kpi"><span className="kpi-label"><CircleAlert size={17}/>{t('text023')}</span><FactValue fact={find('FACT-011')} onEvidence={onEvidence}/><p>{t('text024')}</p></article></div>
  <div className="two-columns"><section className="card conditions-panel"><div className="panel-heading"><div><span className="eyebrow">{t('text025')}</span><h2>{t('text026')}</h2></div><span className="counter">{approved}{t('text013')}</span></div>{baseline.conditions.map((c,i)=>{const f=find(c.factId);const action=baseline.actions.find(a=>a.id===c.actionId);const validated=f?.informationState==='validated';return <div className="condition-row" key={c.id}><span className={`condition-icon ${validated?'done':''}`}>{validated?<Check size={19}/>:i===0?<ShieldCheck size={19}/>:i===1?<UserRound size={19}/>:<FileCheck2 size={19}/>}</span><div><h3>{c.title}</h3><p>{f?.value}</p><div className="condition-meta"><span>{c.owner}</span><Badge state={validated?'validated':f?.informationState??'pending'}/></div><small>{t('text028')}</small><details><summary>{t('text029')}</summary><p>{validated?t('text030'):action?.description}</p>{f?.eventId?<button className="text-button" onClick={()=>onEvidence(f.eventId!)}>{t('text031')}</button>:<EvidenceLinks ids={action?.sourceEvidence??c.evidence} onEvidence={onEvidence}/>}</details></div></div>;})}</section>
  <div className="stack"><section className="card takeaway"><span className="eyebrow">{t('text032')}</span><h2>{t('text033')}<br/>{t('text034')}</h2><p>{find('FACT-005')?.value}{t('text035')}</p><button className="text-button" onClick={()=>onNavigate('contradictions')}>{t('text036')}<ArrowUpRight size={16}/></button><EvidenceLinks ids={factById('FACT-005')?.locators.slice(0,1)??[]} onEvidence={onEvidence}/></section><section className="card finance-panel"><span className="eyebrow">{t('text037')}</span><h2>{t('text038')}</h2><div className="finance-row"><span>{t('text039')}</span><strong>{formatMoney(204000)}</strong></div><div className="finance-row"><span>{t('text041')}</span><strong>{formatMoney(186000)}</strong></div><div className="finance-row"><span>{t('text043')}</span><strong>{formatMoney(132000)}</strong></div><p>{t('text045')}</p><EvidenceLinks ids={['CIT-015','CIT-016','CIT-017']} onEvidence={onEvidence}/></section></div></div>
  <section className="impact-banner"><div className="impact-symbol">{t('text046')}</div><div><span className="eyebrow">{t('text047')}</span><h2>{t('text048')}</h2><p>{t('text049')}</p></div><button className="button light" onClick={()=>onNavigate('impact')}>{t('text050')}<ArrowRight size={17}/></button></section>
  </>;
}
