import {test,expect} from '@playwright/test';
test('homepage explains NOVA, CTAs expose state and exact evidence in two clicks; language switch preserves context',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/MISSING_MESSAGE|INVALID_MESSAGE/.test(m.text()))errors.push(m.text());});
 await page.goto('/fr');await expect(page.getByRole('heading',{name:'Vue d’ensemble',exact:true})).toBeVisible();await expect(page.locator('.dashboard-card')).toHaveCount(6);await expect(page.locator('.about-nova')).toHaveCount(0);await page.goto('/fr/project/overview');
 await page.getByRole('button',{name:'EN',exact:true}).click();await expect(page).toHaveURL(/\/en\/project\/overview/);await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('.kpi').first()).toContainText('October 22');await expect(page.getByRole('button',{name:'Why?',exact:true}).first()).toBeVisible();
 await page.locator('.kpi').first().getByRole('button',{name:'Why?'}).click();await expect(page.getByRole('dialog')).toContainText('ORIGINAL EVIDENCE · FRENCH');await expect(page.getByRole('dialog')).toContainText('TRANSLATED SUMMARY · ENGLISH');await page.keyboard.press('Escape');expect(errors).toEqual([]);
});
test('global command search supports typeahead, filters, highlighting, arrows, Enter and Escape',async({page})=>{
 await page.goto('/en');await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog',{name:'Search NOVA'});await expect(dialog).toBeVisible();await dialog.getByRole('combobox',{name:'Search NOVA',exact:true}).fill('INV-003');await expect(dialog.locator('.search-results').getByRole('option').first()).toBeVisible();await expect(dialog.locator('mark').first()).toBeVisible();await dialog.getByRole('button',{name:/^Questions/}).click();await expect(dialog.locator('.search-results').getByRole('option').first()).toContainText('Questions');await dialog.locator('select').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(dialog.locator('select')).toHaveValue('current');await dialog.locator('select').selectOption('pending');await expect(dialog.locator('.search-results').getByRole('option').first()).toContainText('Pending');await dialog.locator('select').selectOption('all');await dialog.getByRole('combobox',{name:'Search NOVA',exact:true}).focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');await expect(dialog).not.toBeVisible();await expect(page).toHaveURL(/\/en\/questions#Q06/);await expect(page.locator('#Q06')).toContainText('$18,000');
 await page.keyboard.press('Control+k');await expect(dialog).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();
});
test('admin creates, edits and deactivates a bilingual DB question; original evidence stays protected',async({page,browser})=>{
 await page.request.post('/api/auth/login',{headers:{origin:'http://127.0.0.1:3001'},data:{email:'admin@nova.test',password:'Test-only-password-2026'}});
 const fr='Où consulter les preuves de notre atelier?';const en='Where can we find evidence for our workshop?';await page.goto('/fr/admin');await page.getByRole('button',{name:'Ajouter une question'}).click();
 await page.locator('textarea[name=questionFr]').fill(fr);await page.locator('textarea[name=questionEn]').fill(en);await page.locator('textarea[name=answerFr]').fill('Information insuffisante; vérifier les preuves.');await page.locator('textarea[name=answerEn]').fill('Insufficient information; review the evidence.');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Question enregistrée dans la base de données.');
 const row=page.locator('tbody tr').filter({hasText:fr});await expect(row).toBeVisible();const all=await (await page.request.get('/api/admin/questions',{headers:{cookie:'nova_session='+(await page.context().cookies()).find(c=>c.name==='nova_session')!.value}})).json();const stored=all.find((q:{questionFr:string})=>q.questionFr===fr);expect(stored.isOfficial).toBe(false);
 const fresh=await browser.newContext();const freshPage=await fresh.newPage();await freshPage.goto('/en/questions');await expect(freshPage.getByRole('heading',{name:en,exact:true})).toBeVisible();await expect(freshPage.locator('[id="'+stored.id+'"]')).toContainText('Team-curated content');await freshPage.setViewportSize({width:390,height:844});expect(await freshPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await fresh.close();
 await row.getByRole('button',{name:'Modifier',exact:true}).click();await page.locator('textarea[name=answerEn]').fill('Updated explanation requiring evidence.');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Question enregistrée dans la base de données.');
 await page.goto('/en/search');await page.getByRole('combobox',{name:'Search NOVA',exact:true}).fill('workshop');await page.getByRole('button',{name:/^Questions/}).click();await expect(page.locator('.search-results').getByRole('option').filter({hasText:en})).toBeVisible();
 await page.goto('/en/admin');const editRow=page.locator('tbody tr').filter({hasText:en});await editRow.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('checkbox',{name:'Active',exact:true}).uncheck();await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Question saved to the database.');await page.goto('/en/questions');await expect(page.getByRole('heading',{name:en,exact:true})).toHaveCount(0);
 expect((await page.request.put('/api/admin/questions/Q01',{headers:{origin:'http://127.0.0.1:3001',cookie:'nova_session='+(await page.context().cookies()).find(c=>c.name==='nova_session')!.value},data:stored})).status()).toBe(403);
});
test('all critical English screens render translated headings without i18n key leakage, at desktop and tablet',async({page})=>{
 const errors:string[]=[];page.on('console',m=>{if(m.type()==='error'&&/MISSING_MESSAGE|INVALID_MESSAGE/.test(m.text()))errors.push(m.text());});
 await page.request.post('/api/auth/login',{headers:{origin:'http://127.0.0.1:3001'},data:{email:'admin@nova.test',password:'Test-only-password-2026'}});
 const screens=[['project/timeline','Project timeline'],['project/decisions','Decisions you can explain'],['project/contradictions','Resolving contradictions'],['actions','Next actions'],['evidence','Evidence explorer'],['questions','Answers you can verify'],['ask','Ask NOVA'],['impact','Impact Mode'],['admin','NOVA 360 Administration'],['brief','The project takeover brief']];
 for(const [route,heading]of screens){await page.goto('/en/'+route);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();expect(await page.locator('main').innerText()).not.toMatch(/(?:ui\.text\d|nav\.|home\.|states\.|engine\.reason)/);}
 await page.goto('/en/ask');await page.getByRole('button',{name:'Has security been accepted?',exact:true}).click();await expect(page.locator('.question-card').first()).toContainText('SEC-210 remains IN VALIDATION');
 await page.setViewportSize({width:820,height:1180});for(const route of ['','project/overview','questions','admin','search']){await page.goto('/en/'+route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route).toBe(true);}expect(errors).toEqual([]);
 await page.screenshot({path:'artifacts/home-tablet-en.png',fullPage:true});
});
test('English Impact distinguishes proposal, correction announcement and validation without closing unrelated conditions',async({page})=>{
 await page.goto('/en/impact');await page.getByLabel('Content received from the judges').fill('Julien proposes the launch date of October 15.');await page.getByLabel('Source / locator').fill('Synthetic English browser fixture');await page.getByLabel('Author / authority',{exact:true}).fill('Test author');await page.getByRole('button',{name:'Analyze candidates'}).click();await expect(page.getByLabel('Information state')).toHaveValue('proposed');await page.getByRole('checkbox').check();await expect(page.getByText('Proposal retained; no approved decision replaced.',{exact:true})).toBeVisible();
 await page.getByLabel('Content received from the judges').fill('ACC-303 correction announced for the next build.');await page.getByRole('button',{name:'Analyze candidates'}).click();await expect(page.getByLabel('Information state')).toHaveValue('uncertain');await page.getByRole('checkbox').check();await expect(page.getByText('Insufficient information: no automatic replacement.',{exact:true})).toBeVisible();
 await page.getByLabel('Content received from the judges').fill('ACC-303 validated and accepted by Mélissa after keyboard retest.');await page.getByRole('button',{name:'Analyze candidates'}).click();await expect(page.getByLabel('Information state')).toHaveValue('validated');await page.getByRole('checkbox').check();await expect(page.getByRole('heading',{name:/1 changeable fact/})).toBeVisible();await page.getByRole('button',{name:'Save event and impacts'}).click();await expect(page.getByRole('status')).toContainText('Event saved.');await page.goto('/en/project/overview');await expect(page.locator('.orbit-ring strong')).toHaveText('2/ 3');await expect(page.locator('.condition-row').last()).toContainText('Incomplete');await expect(page.locator('.kpi').first()).toContainText('October 22');await page.getByRole('button',{name:'Baseline',exact:true}).click();await expect(page.locator('.orbit-ring strong')).toHaveText('0/ 3');

});
test('an earlier browser journal can be explicitly migrated without changing its original content or baseline',async({page,request})=>{
 const event={id:'LEGACY-e2e',receivedAt:'2026-09-30T16:00:00Z',occurredAt:'2026-09-30T12:00:00-04:00',source:'Synthetic legacy browser journal',author:'Test author',text:'A proposed date remains a proposal.',candidates:[{factId:'FACT-002',value:'October 15 proposed',state:'proposed',excerpt:'A proposed date remains a proposal.',confirmed:true}]};
 await page.addInitScript(value=>localStorage.setItem('nova360.events.v1',JSON.stringify([value])),event);await page.goto('/en');await expect(page.getByRole('button',{name:'Import my earlier journal',exact:true})).toBeVisible();await page.getByRole('button',{name:'Import my earlier journal',exact:true}).click();await expect(page.getByRole('button',{name:'Import my earlier journal',exact:true})).toHaveCount(0);expect(JSON.parse(await page.evaluate(()=>localStorage.getItem('nova360.events.v1')!))).toEqual([event]);
 expect((await (await request.get('/api/events')).json()).some((e:{id:string})=>e.id===event.id)).toBe(true);await page.goto('/en/project/overview');await expect(page.locator('.kpi').first()).toContainText('October 22');await page.getByRole('button',{name:'Baseline',exact:true}).click();await expect(page.locator('.orbit-ring strong')).toHaveText('0/ 3');await page.getByRole('button',{name:'FR',exact:true}).click();await expect(page).toHaveURL(/\/fr\/project\/overview\?view=baseline/);await expect(page.locator('.orbit-ring strong')).toHaveText('0/ 3');
});

test('malformed older browser journal is reported without altering database events',async({page,request})=>{const before=await (await request.get('/api/events')).json();await page.addInitScript(()=>localStorage.setItem('nova360.events.v1','invalid JSON'));await page.goto('/en');await expect(page.locator('.notice[role=alert]')).toContainText('Earlier browser journal unreadable or unavailable');expect(await (await request.get('/api/events')).json()).toEqual(before);await page.getByRole('button',{name:'Baseline',exact:true}).click();await expect(page.locator('.dashboard-grid')).toContainText('0 / 3');});
