import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:3001';
const admin={email:'admin@nova.test',password:'Test-only-password-2026'};
test('server guards admin children, aliases and APIs; registration defaults USER; logout invalidates session',async({page})=>{
 await page.goto('/fr/admin/nested');await expect(page).toHaveURL(/\/fr\/login/);await expect(page.getByRole('heading',{name:'Connexion',exact:true})).toBeVisible();
 expect((await page.request.get('/api/admin/questions')).status()).toBe(401);expect((await page.request.post('/api/admin/questions',{headers:{origin},data:{}})).status()).toBe(401);
 await page.goto('/en/register');await page.screenshot({path:'artifacts/iteration3-register-en.png'});await page.getByLabel('Name',{exact:true}).fill('Judge User');await page.getByLabel('Email',{exact:true}).fill('judge@nova.test');await page.getByLabel('Password',{exact:true}).fill('Judge-password-2026');await page.getByLabel('Confirm password').fill('Judge-password-2026');await page.getByRole('button',{name:'Register',exact:true}).click();await expect(page).toHaveURL('/en');await expect(page.locator('.header-account')).toContainText('USER');await expect(page.getByRole('button',{name:'Question Bank (Admin)',exact:true})).toHaveCount(0);
 const cookie=(await page.context().cookies()).find(c=>c.name==='nova_session')!;expect(cookie.httpOnly).toBe(true);expect(cookie.sameSite).toBe('Lax');expect(cookie.secure).toBe(true);
 expect((await page.request.get('/api/admin/users',{headers:{cookie:'nova_session='+cookie.value}})).status()).toBe(403);expect((await page.request.post('/api/admin/questions',{headers:{origin,cookie:'nova_session='+cookie.value},data:{}})).status()).toBe(403);await page.goto('/en/admin/users');await expect(page.getByRole('heading',{name:'Access denied'})).toBeVisible();await page.goto('/en/?page=admin');await expect(page.getByRole('heading',{name:'Access denied'})).toBeVisible();
 const savedCookie=cookie.value;expect((await page.request.post('/api/auth/logout',{headers:{origin,cookie:'nova_session='+cookie.value}})).ok()).toBe(true);expect((await page.request.get('/api/admin/users',{headers:{cookie:'nova_session='+savedCookie}})).status()).toBe(401);
 await page.goto('/fr/register');await expect(page.getByLabel('Nom',{exact:true})).toBeVisible();await expect(page.getByLabel('Confirmer le mot de passe')).toBeVisible();await page.goto('/en/login');await page.screenshot({path:'artifacts/iteration3-login-en.png'});await page.getByLabel('Email',{exact:true}).fill('judge@nova.test');await page.getByLabel('Password',{exact:true}).fill('wrong');await page.getByRole('button',{name:'Login',exact:true}).click();await expect(page.locator('#auth-error')).toContainText('Invalid credentials');
});
test('admin login, user search/deactivation and CSRF protection',async({page})=>{
 await page.goto('/fr/login');await page.screenshot({path:'artifacts/iteration3-login-fr.png'});await page.getByLabel('Courriel',{exact:true}).fill(admin.email);await page.getByLabel('Mot de passe',{exact:true}).fill(admin.password);await page.getByRole('button',{name:'Connexion',exact:true}).click();await expect(page).toHaveURL('/fr');await page.getByRole('button',{name:'Utilisateurs',exact:true}).click();await expect(page.getByRole('heading',{name:'Utilisateurs',exact:true})).toBeVisible();const users=await (await page.request.get('/api/admin/users',{headers:{cookie:'nova_session='+(await page.context().cookies()).find(c=>c.name==='nova_session')!.value}})).json();expect(users.length).toBeGreaterThan(1);expect(users[0]).not.toHaveProperty('passwordHash');await page.getByLabel('Rechercher un utilisateur').fill('Judge');const row=page.locator('tbody tr').filter({hasText:'judge@nova.test'});await row.getByRole('button',{name:'Désactiver',exact:true}).click();await expect(row).toContainText('Inactif');
 expect((await page.request.post('/api/auth/login',{headers:{origin},data:{email:'judge@nova.test',password:'Judge-password-2026'}})).status()).toBe(401);
 expect((await page.request.patch('/api/admin/users',{headers:{origin:'https://evil.test',cookie:'nova_session='+(await page.context().cookies()).find(c=>c.name==='nova_session')!.value},data:{id:'x',active:false}})).status()).toBe(403);
 await page.getByLabel('Rechercher un utilisateur').fill('admin@nova.test');await page.locator('tbody tr').getByRole('button',{name:'Désactiver',exact:true}).click();await expect(page.locator('main').getByRole('alert')).toContainText('Impossible');
 await page.getByRole('button',{name:'Question Bank (Admin)',exact:true}).click();await expect(page.locator('thead')).not.toContainText('FR');await expect(page.locator('thead')).not.toContainText('EN');await expect(page.locator('tbody tr').first()).toBeVisible();await page.screenshot({path:'artifacts/iteration3-question-bank.png',fullPage:true});
});
test('bilingual support, mascot, keyboard close and responsive clean dashboard',async({page})=>{
 for(const [locale,title,prompt,reply] of [['fr','Support IA','Où sont les risques?','Consultez les risques'],['en','AI Support','Where are the risks?','Open Risks']]){await page.goto('/'+locale);await page.screenshot({path:'artifacts/iteration3-home-'+locale+'-desktop.png',fullPage:true});await expect(page.locator('.dashboard-card')).toHaveCount(6);await expect(page.locator('.about-nova')).toHaveCount(0);await expect(page.locator('.support-launch img')).toBeVisible();expect(await page.locator('.support-launch img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);await page.getByRole('button',{name:title,exact:true}).click();const panel=page.getByRole('dialog',{name:title});await page.screenshot({path:'artifacts/iteration3-chat-'+locale+'.png'});await panel.getByRole('button',{name:prompt,exact:true}).click();await expect(panel.getByRole('log')).toContainText(reply);await expect(panel.getByRole('link')).toHaveAttribute('href','/'+locale+'/project/contradictions');await page.keyboard.press('Escape');await expect(panel).not.toBeVisible();await page.setViewportSize({width:390,height:844});await expect(page.getByRole('button',{name:title,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/iteration3-'+locale+'-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});}
});



test('French registration and English login; header question routes to existing factual Ask NOVA',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/fr/register');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/iteration3-register-fr.png',fullPage:true});await page.getByLabel('Nom',{exact:true}).fill('Utilisateur FR');await page.getByLabel('Courriel',{exact:true}).fill('fr-user@nova.test');await page.getByLabel('Mot de passe',{exact:true}).fill('French-password-2026');await page.getByLabel('Confirmer le mot de passe').fill('French-password-2026');await page.getByRole('button',{name:'Créer un compte',exact:true}).click();await expect(page).toHaveURL('/fr');await page.locator('.header-account summary').click();await page.getByRole('button',{name:'Déconnexion',exact:true}).click();await expect(page.locator('.header-account')).toContainText('Connexion');await page.goto('/en/login');await page.screenshot({path:'artifacts/iteration3-login-en.png'});await page.getByLabel('Email',{exact:true}).fill('fr-user@nova.test');await page.getByLabel('Password',{exact:true}).fill('French-password-2026');await page.getByRole('button',{name:'Login',exact:true}).click();await expect(page).toHaveURL('/en');await page.getByRole('textbox',{name:'Ask a question in natural language...'}).fill('INV-003');await page.getByRole('textbox',{name:'Ask a question in natural language...'}).press('Enter');await expect(page).toHaveURL(/\/en\/ask\?q=INV-003/);await expect(page.locator('#Q06')).toContainText('$18,000');await page.screenshot({path:'artifacts/iteration3-desktop-en.png',fullPage:true});
});

test('evidence has one global locale control, source/locator retained, mascot fallback and chat focus trap',async({page})=>{
 await page.goto('/fr/evidence?citation=CIT-004');const evidence=page.getByRole('dialog',{name:'Preuve et repère précis'});await expect(evidence).toBeVisible();await expect(evidence.locator('.locator-callout')).toContainText('CIT-004');await expect(evidence.getByRole('button',{name:'FR',exact:true})).toHaveCount(0);await expect(evidence.getByRole('button',{name:'EN',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await page.getByRole('button',{name:'EN',exact:true}).click();await expect(page).toHaveURL(/\/en\/evidence/);await expect(page.locator('html')).toHaveAttribute('lang','en');
 await page.route('**/_next/image*',route=>route.abort());await page.goto('/en');await expect(page.locator('.support-launch .mascot-fallback')).toBeVisible();await page.getByRole('button',{name:'AI Support',exact:true}).click();const chat=page.getByRole('dialog',{name:'AI Support'});await chat.getByRole('textbox').fill('xyzzy');await chat.getByRole('button',{name:'Send',exact:true}).click();await expect(chat.getByRole('log')).toContainText('Ask NOVA');await page.keyboard.press('Tab');expect(await chat.evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.keyboard.press('Escape');await expect(chat).not.toBeVisible();
});
