'use client';
import {useEffect,useState} from 'react';
import {useTranslations,useLocale} from 'next-intl';
import {useProject} from '@/lib/project-context';
import type {QuestionInput} from '@/lib/repositories/questions';
import {Plus,LockKeyhole,Save} from 'lucide-react';
type Row=QuestionInput&{id:string;isOfficial:boolean;updatedAt:string;citations:{citationId:string}[]};
const empty:QuestionInput={questionFr:'',questionEn:'',answerFr:'',answerEn:'',nuanceFr:'',nuanceEn:'',status:'uncertain',active:true,sortOrder:100,tags:'',evidence:[]};
export function AdminPage({onSaved}:{onSaved:()=>void}){
 const t=useTranslations('admin');const n=useTranslations('nav');const locale=useLocale();const {citations,labels}=useProject();const [rows,setRows]=useState<Row[]>([]);const [edit,setEdit]=useState<QuestionInput|null>(null);const [id,setId]=useState<string>();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{try{const response=await fetch('/api/admin/questions');if(!response.ok)throw new Error();setRows(await response.json());}catch{setMessage(t('loadError'));}};
 useEffect(()=>{let active=true;fetch('/api/admin/questions').then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{if(active)setRows(data);}).catch(()=>{if(active)setMessage(t('loadError'));});return ()=>{active=false;};},[t]);
 const update=(patch:Partial<QuestionInput>)=>setEdit(e=>e?{...e,...patch}:e);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!edit)return;setBusy(true);setMessage('');try{const response=await fetch('/api/admin/questions'+(id?'/'+encodeURIComponent(id):''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});if(!response.ok)throw new Error();setMessage(t('saved'));setEdit(null);await load();onSaved();}catch{setMessage(t('error'));}finally{setBusy(false);}};
 return <><div className="section-heading"><div><span className="eyebrow">NOVA 360</span><h1>{t('title')}</h1><p>{t('intro')}</p></div><button className="button primary" onClick={()=>{setId(undefined);setEdit({...empty,evidence:[]});setMessage('');}}><Plus size={18}/>{t('add')}</button></div><div className="notice"><LockKeyhole size={18}/>{t('local')}</div>{message&&<p role="status" className="notice">{message}</p>}
 {edit?<form onSubmit={submit} className="card question-editor"><h2>{id?t('editTitle'):t('new')}</h2><p>{t('required')}</p><div className="bilingual-editor">{['Fr','En'].map(lang=><fieldset key={lang}><legend>{lang==='Fr'?'FR':'EN'}</legend>{['question','answer','nuance'].map(field=>{const key=(field+lang) as keyof QuestionInput;return <label key={key}>{t(key)}{field!=='nuance'?' *':''}<textarea name={key} value={edit[key] as string} required={field!=='nuance'} maxLength={20000} rows={field==='question'?2:4} onChange={e=>update({[key]:e.target.value})}/></label>;})}</fieldset>)}</div><div className="form-grid"><label>{t('status')}<select value={edit.status} onChange={e=>update({status:e.target.value})}>{['uncertain','current','approved','pending','validated','historical','proposed','delivered','implemented'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>{t('order')}<input type="number" min={0} max={10000} value={edit.sortOrder} onChange={e=>update({sortOrder:Number(e.target.value)})}/></label><label>{t('tags')}<input value={edit.tags} onChange={e=>update({tags:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={edit.active} onChange={e=>update({active:e.target.checked})}/>{t('active')}</label></div><fieldset className="citation-picker"><legend>{t('evidence')}</legend>{citations.map(c=><label className="checkbox-label" key={c.id}><input type="checkbox" checked={edit.evidence.includes(c.id)} onChange={e=>update({evidence:e.target.checked?[...edit.evidence,c.id]:edit.evidence.filter(id=>id!==c.id)})}/><span><strong>{c.id} · {c.sourceId}</strong><small>{c.locator}</small><span>{c.excerptSummary}</span></span></label>)}</fieldset><div className="button-row"><button className="button primary" disabled={busy}><Save size={17}/>{t('save')}</button><button type="button" className="button secondary" onClick={()=>setEdit(null)}>{t('cancel')}</button></div><small>{t('audit')}</small></form>:<section className="card"><h2>{t('questions')}</h2><div className="table-scroll"><table className="admin-table"><thead><tr><th>{t('questions')}</th><th>{t('type')}</th><th>{t('status')}</th><th>{t('updated')}</th><th>{t('edit')}</th></tr></thead><tbody>{rows.map(q=><tr key={q.id}><td>{locale==='en'?q.questionEn:q.questionFr}</td><td>{q.isOfficial?n('official'):n('custom')}</td><td>{q.active?t('active'):t('inactive')}</td><td>{new Intl.DateTimeFormat(locale==='en'?'en-CA':'fr-CA',{dateStyle:'short',timeStyle:'short'}).format(new Date(q.updatedAt))}</td><td>{q.isOfficial?<small><LockKeyhole size={14}/>{t('protected')}</small>:<button className="text-button" onClick={()=>{setId(q.id);setEdit({...q,evidence:q.citations.map(c=>c.citationId)});setMessage('');}}>{t('edit')}</button>}</td></tr>)}</tbody></table></div></section>}</>;
}
