'use client';
import {useEffect,useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {useRouter,usePathname,useSearchParams} from 'next/navigation';
import {Search,Menu,X,LockKeyhole,GitCompareArrows,ChevronDown} from 'lucide-react';
import {useProject} from '@/lib/project-context';
import type {ProjectEvent} from '@/lib/impact';
import type {SearchResult} from '@/lib/repositories/search';
import {Overview} from './overview';
import {TimelinePage,NewEventsTimeline,DecisionsPage,ActionsPage,ContradictionsPage,QuestionsPage} from './project-pages';
import {EvidenceExplorer,EvidenceModal} from './evidence';
import {ImpactPage} from './impact-page';
import {AskPage} from './ask-page';
import {Brief} from './brief';
import {HomePage} from './home';
import {SearchExperience,SearchPalette} from './search';
import {AdminPage} from './admin';
const route:Record<string,string>={home:'',overview:'project/overview',timeline:'project/timeline',decisions:'project/decisions',contradictions:'project/contradictions',actions:'actions',evidence:'evidence',questions:'questions',search:'search',ask:'ask',impact:'impact',brief:'brief',admin:'admin'};
export function Hub({initialPage}:{initialPage:string}){
 const t=useTranslations('nav');const s=useTranslations('search');const locale=useLocale();const router=useRouter();const pathname=usePathname();const params=useSearchParams();const {baseline,canonicalBaseline,deriveCurrent,displayFacts,isProjectEvent}=useProject();const page=route[initialPage]!==undefined?initialPage:'home';
 const [legacy,setLegacy]=useState<ProjectEvent[]>([]);const [citation,setCitation]=useState<string|null>(null);const [events,setEvents]=useState<ProjectEvent[]>([]);const [loaded,setLoaded]=useState(false);const [view,setView]=useState(params.get('view')==='baseline'?'baseline':'current');const [mobile,setMobile]=useState(false);const [notice,setNotice]=useState('');const [searchOpen,setSearchOpen]=useState(false);
 useEffect(()=>{const abort=new AbortController();fetch('/api/events',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{setEvents(data);setLoaded(true);try{const raw=localStorage.getItem('nova360.events.v1');if(raw){const previous=JSON.parse(raw);if(!Array.isArray(previous)||previous.length>200||!previous.every(isProjectEvent))throw new Error('legacy');if(previous.some((e:ProjectEvent)=>!data.some((current:ProjectEvent)=>current.id===e.id)))setLegacy(previous);}}catch{setNotice(t('legacyError'));}}).catch(()=>{if(!abort.signal.aborted){setNotice(t('loadingError'));setView('baseline');}});return ()=>abort.abort();},[t,isProjectEvent]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setSearchOpen(open=>!open);}};window.addEventListener('keydown',handler);return ()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('citation'))setTimeout(()=>setCitation(params.get('citation')),0);},[pathname]);
 const current=useMemo(()=>deriveCurrent(events),[deriveCurrent,events]);const facts=displayFacts(view==='baseline'?canonicalBaseline.facts:current);
 const navigate=(next:string,params?:Record<string,string>,anchor?:string)=>{setMobile(false);const nextQuery=new URLSearchParams(params);if(view==='baseline')nextQuery.set('view','baseline');const query=nextQuery.toString();router.push('/'+locale+'/'+(route[next]??'')+(query?'?'+query:'')+(anchor?'#'+anchor:''));};
 const persist=async(incoming:ProjectEvent[])=>{try{const response=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:incoming,locale})});if(!response.ok)throw new Error();setEvents(await response.json());setLoaded(true);return true;}catch{setNotice(t('eventError'));return false;}};
 const openResult=(result:SearchResult)=>{if(result.citationId){setCitation(result.citationId);return;}navigate(result.page,result.sourceId?{source:result.sourceId}:undefined,result.anchor);};
 const changeView=(next:string)=>{setView(next);const query=new URLSearchParams(params.toString());if(next==='baseline')query.set('view',next);else query.delete('view');router.replace(pathname+(query.size?'?'+query.toString():''),{scroll:false});};
 const closeEvidence=()=>{setCitation(null);if(params.has('citation')){const query=new URLSearchParams(params.toString());query.delete('citation');router.replace(pathname+(query.size?'?'+query.toString():''),{scroll:false});}};
 const switchLocale=(next:string)=>{const query=new URLSearchParams(window.location.search);if(view==='baseline')query.set('view','baseline');else query.delete('view');router.push(pathname.replace(/^\/(fr|en)(?=\/|$)/,'/'+next)+(query.size?'?'+query.toString():'')+window.location.hash);};
 const projectPages=['overview','timeline','decisions','contradictions'];const primary=['home','project','actions','evidence','search'];
 return <div className="nova-app"><a className="skip-link" href="#main">{t('skip')}</a><header className="enterprise-header"><div className="institution-bar"><strong>Loto-Québec</strong><span>{t('projectLabel')}</span><div className="language-switch" aria-label={t('language')}>{['fr','en'].map(lang=><button key={lang} lang={lang} aria-pressed={locale===lang} onClick={()=>switchLocale(lang)}>{lang.toUpperCase()}</button>)}</div></div><div className="product-bar"><button className="product-brand" onClick={()=>navigate('home')}>NOVA <span>360</span><small>PROJECT INTELLIGENCE HUB</small></button><button className="menu-toggle icon-button" aria-label={mobile?t('close'):t('menu')} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><nav className={mobile?'primary-nav open':'primary-nav'} aria-label={t('primary')}>{primary.map(id=><button key={id} className={(id==='project'?projectPages.includes(page):id==='evidence'?['evidence','questions'].includes(page):id===page)?'active':''} onClick={()=>navigate(id==='project'?'overview':id)}>{t(id)}</button>)}<details className="tools-menu"><summary>{t('tools')}<ChevronDown size={14}/></summary><div>{['impact','ask','brief','admin'].map(id=><button key={id} onClick={()=>navigate(id)}>{t(id)}</button>)}</div></details></nav><button className="header-search" onClick={()=>setSearchOpen(true)}><Search size={18}/><span>{s('open')}</span></button></div></header>
 <div className="project-context-bar"><div><LockKeyhole size={14}/><span>{t('baseline')} · {new Intl.DateTimeFormat(locale==='en'?'en-CA':'fr-CA',{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'America/Montreal'}).format(new Date(baseline.asOf))}</span></div><div className="state-toggle"><button aria-pressed={view==='baseline'} className={view==='baseline'?'active':''} onClick={()=>changeView('baseline')}>{t('baselineView')}</button><button aria-pressed={view==='current'} className={view==='current'?'active':''} onClick={()=>changeView('current')}>{t('current')}{events.length>0&&<span>{events.length}</span>}</button><button aria-label={t('compare')} onClick={()=>navigate('impact')}><GitCompareArrows size={17}/></button></div></div>
 {projectPages.includes(page)&&<nav className="secondary-nav" aria-label={t('project')}>{projectPages.map(id=><button className={page===id?'active':''} key={id} onClick={()=>navigate(id)}>{t(id)}</button>)}</nav>}{['evidence','questions'].includes(page)&&<nav className="secondary-nav" aria-label={t('evidence')}>{['evidence','questions'].map(id=><button className={page===id?'active':''} key={id} onClick={()=>navigate(id)}>{t(id)}</button>)}</nav>}
 <main id="main" tabIndex={-1} className="enterprise-main">{!loaded&&view==='current'&&<p role="status" className="notice">{t('loading')}</p>}{legacy.length>0&&<div className="notice">{t('legacy')}<button className="text-button" onClick={async()=>{if(await persist(legacy))setLegacy([]);}}>{t('importLegacy')}</button></div>}{notice&&<div className="notice" role="alert">{notice}<button className="text-button" onClick={()=>setNotice('')}>{t('close')}</button></div>}{view==='baseline'&&events.length>0&&<div className="notice">{t('baselineNotice')}</div>}
 {page==='home'&&<HomePage facts={facts} onNavigate={navigate} onEvidence={setCitation}/>}{page==='overview'&&<Overview facts={facts} onEvidence={setCitation} onNavigate={navigate}/>}{page==='timeline'&&<><TimelinePage onEvidence={setCitation}/><NewEventsTimeline events={view==='baseline'?[]:events} onEvidence={setCitation}/></>}{page==='decisions'&&<DecisionsPage onEvidence={setCitation}/>}{page==='actions'&&<ActionsPage facts={facts} onEvidence={setCitation}/>}{page==='contradictions'&&<ContradictionsPage onEvidence={setCitation} facts={facts}/>}{page==='evidence'&&<EvidenceExplorer onEvidence={setCitation}/>}{page==='questions'&&<QuestionsPage facts={facts} onEvidence={setCitation}/>}{page==='ask'&&<AskPage facts={facts} onEvidence={setCitation} onNavigate={navigate}/>}{page==='impact'&&loaded&&<ImpactPage events={events} facts={current} onAppend={event=>persist([event])} onImport={persist} onEvidence={setCitation}/>}{page==='brief'&&<Brief facts={facts}/>}{page==='search'&&<SearchExperience onOpen={openResult}/>}{page==='admin'&&<AdminPage onSaved={()=>router.refresh()}/>}
 <footer className="app-footer"><span>NOVA 360 · Project Intelligence Hub</span><span>{t('footer')}</span></footer></main><EvidenceModal view={view} citationId={citation} onClose={closeEvidence} onEvidence={setCitation} events={events}/><SearchPalette open={searchOpen} onClose={()=>setSearchOpen(false)} onOpen={openResult}/></div>;
}
