'use client';
import {useTranslations} from 'next-intl';
import {useProject} from '@/lib/project-context';
import { useState, useMemo } from 'react';
import { ArrowRight, GitCompareArrows, LockKeyhole, Plus, Save, Download, Upload, CircleAlert } from 'lucide-react';

import {eventStates,type ProjectEvent,type Candidate,type DerivedFact} from '@/lib/impact';
import { Badge, SectionHeading, type EvidenceHandler, EvidenceLinks } from './primitives';
export function ImpactPage({events,facts,onAppend,onImport,onEvidence}: {events:ProjectEvent[];facts:DerivedFact[];onAppend:(event:ProjectEvent)=>Promise<boolean>;onImport:(events:ProjectEvent[])=>Promise<boolean>;onEvidence:EvidenceHandler}) {
 const t=useTranslations('ui');const {baseline,labels,analyzeEvent,actionState,deriveCurrent,displayFacts,parseCandidates,isProjectEvent}=useProject();

  const [text,setText]=useState('');const [source,setSource]=useState('');const [author,setAuthor]=useState('');
  const [occurredAt,setOccurredAt]=useState('2026-09-30T10:00');const [candidates,setCandidates]=useState<Candidate[]>([]);
  const [analyzed,setAnalyzed]=useState(false);const [message,setMessage]=useState('');const [tab,setTab]=useState('event');
  const [manualId,setManualId]=useState('FACT-002');
  const [newSubject,setNewSubject]=useState('');
  const event:ProjectEvent=useMemo(()=>({id:'PREVIEW',receivedAt:new Date().toISOString(),occurredAt:occurredAt?occurredAt+':00-04:00':'',source,author,text,candidates}),[text,source,author,occurredAt,candidates]);
  const impact=analyzeEvent(facts,event);
  const previewFacts=[...facts.map(f=>impact.changed.find(x=>x.before.id===f.id)?.after??f),...impact.newFacts];
  const edit=(i:number,patch:Partial<Candidate>)=>setCandidates(prev=>prev.map((c,index)=>index===i?{...c,...patch}:c));
  const save=async()=>{
    if(!source.trim()||!author.trim()||!text.trim()||!occurredAt){setMessage(t('text154'));return;}
    if(!candidates.length){setMessage(t('text155'));return;}
    const record={...event,id:'JUDGE-'+crypto.randomUUID(),receivedAt:new Date().toISOString()};
    if(!isProjectEvent(record)){setMessage(t('text156'));return;}
    if(await onAppend(record)){setMessage(t('text157'));setCandidates([]);setText('');setAnalyzed(false);}
    else setMessage(t('text158'));
  };
  const exportJournal=()=>{
    const blob=new Blob([JSON.stringify({schemaVersion:1,baselineId:baseline.id,baselineAsOf:baseline.asOf,events},null,2)],{type:'application/json'});
    const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='nova360-events.json';a.click();URL.revokeObjectURL(url);
  };
  const importJournal=async(file:File|undefined)=>{
    if(!file)return;
    try{
      if(file.size>5_000_000)throw new Error(t('text159'));
      const value=JSON.parse(await file.text());
      if(value.schemaVersion!==1||value.baselineId!==baseline.id||value.baselineAsOf!==baseline.asOf||!Array.isArray(value.events)||value.events.length>200||!value.events.every(isProjectEvent))throw new Error(t('text160'));
      const unique=new Set(value.events.map((e:ProjectEvent)=>e.id));if(unique.size!==value.events.length)throw new Error(t('text161'));
      if(await onImport(value.events))setMessage(t('text162'));else throw new Error(t('text163'));
    }catch(error){setMessage(error instanceof Error?error.message:t('text164'));}
  };
  return <><SectionHeading eyebrow={t('text165')} title={t('text166')} description={t('text167')}><span className="baseline-lock"><LockKeyhole size={14}/>{t('text168')}</span></SectionHeading>
  <div className="segmented">{[['event',t('text169')],['compare',t('text170')],['journal',t('text171',{v0:events.length})]].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {message&&<div className="notice" role="status">{message}</div>}
  {tab==='event'&&<div className="impact-workspace"><section className="card event-input"><span className="eyebrow">{t('text172')}</span><h2>{t('text173')}</h2><label>{t('text174')}<textarea value={text} maxLength={20000} rows={7} onChange={e=>{setText(e.target.value);setAnalyzed(false);}} placeholder={t('text175')}/></label><div className="form-grid"><label>{t('text176')}<input value={source} onChange={e=>setSource(e.target.value)} placeholder={t('text177')} maxLength={500}/></label><label>{t('text178')}<input value={author} onChange={e=>setAuthor(e.target.value)} placeholder={t('text179')} maxLength={500}/></label></div><label>{t('text180')}<input type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><button className="button primary" disabled={!text.trim()} onClick={()=>{setCandidates(parseCandidates(text));setAnalyzed(true);setMessage('');}}><GitCompareArrows size={16}/>{t('text181')}</button><p className="small muted">{t('text182')}</p></section>
  <section className="card candidate-panel"><span className="eyebrow">{t('text183')}</span><h2>{t('text184')}</h2>{!analyzed?<div className="empty-state"><GitCompareArrows size={36}/><p>{t('text185')}</p><small>{t('text186')}</small></div>:<>
  {!candidates.length&&<div className="notice">{t('text187')}</div>}
  {candidates.map((c,i)=><div className="candidate" key={c.factId+'-'+i}><label>{t('text188')}<select value={c.factId} onChange={e=>edit(i,{factId:e.target.value,confirmed:false})}>{c.newSubject&&<option value={c.factId}>{c.factId} · {c.newSubject}</option>}{baseline.facts.filter(f=>f.informationState!=='historical').map(f=><option key={f.id} value={f.id}>{f.id} · {f.subject}{t('text189')}{f.predicate}</option>)}</select></label><label>{t('text190')}<textarea rows={2} value={c.value} onChange={e=>edit(i,{value:e.target.value,confirmed:false})}/></label><label>{t('text191')}<select value={c.state} onChange={e=>edit(i,{state:e.target.value as Candidate['state'],confirmed:false})}>{eventStates.map(s=><option value={s} key={s}>{labels[s]}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={c.confirmed} onChange={e=>edit(i,{confirmed:e.target.checked})}/><span>{t('text192')}</span></label><button className="text-button" onClick={()=>setCandidates(prev=>prev.filter((_,j)=>j!==i))}>{t('text193')}</button></div>)}
  <label>{t('text194')}<input value={newSubject} maxLength={500} onChange={e=>setNewSubject(e.target.value)} placeholder={t('text195')}/></label><button className="button secondary" disabled={!newSubject.trim()||!text.trim()} onClick={()=>{setCandidates(prev=>[...prev,{factId:"NEW-"+crypto.randomUUID(),newSubject:newSubject.trim(),value:text,state:"uncertain",excerpt:text,confirmed:false}]);setNewSubject("");}}><Plus size={14}/>{t('text196')}</button><p className="small muted">{t('text197')}</p><div className="manual-candidate"><select aria-label={t('text198')} value={manualId} onChange={e=>setManualId(e.target.value)}>{baseline.facts.filter(f=>f.informationState!=='historical').map(f=><option value={f.id} key={f.id}>{f.subject} · {f.predicate}</option>)}</select><button className="button secondary" onClick={()=>setCandidates(prev=>[...prev,{factId:manualId,value:text,state:'uncertain',excerpt:text,confirmed:false}])}><Plus size={14}/>{t('text199')}</button></div></>}
  </section></div>}
  {tab==='event'&&analyzed&&<section className="card impact-results"><span className="eyebrow">{t('text200')}</span><h2>{t('summary',{changed:impact.changed.length,unchanged:impact.unchanged.length})}</h2>{impact.changed.map(x=><div className="diff-row" key={x.before.id}><div><small>{t('text203')}</small><strong>{x.before.subject}</strong><p>{x.before.value}</p><Badge state={x.before.informationState}/></div><ArrowRight size={20}/><div><small>{t('text204')}</small><p>{x.after.value}</p><Badge state={x.after.informationState}/><small>{x.reason}</small></div></div>)}
  {impact.newFacts.length>0&&<><h3>{t('text205')}{impact.newFacts.length}{t('text128')}</h3>{impact.newFacts.map(f=><div className="notice" key={f.id}><strong>{f.subject}</strong><p>{f.value}</p><Badge state={f.informationState}/><small>{t('text206')}</small></div>)}</>}{impact.pending.length>0&&<><h3><CircleAlert size={16}/>{t('text207')}</h3>{impact.pending.map((p,i)=><div className="pending-row" key={i}><Badge state={p.candidate.state}/><strong>{baseline.facts.find(f=>f.id===p.candidate.factId)?.subject}</strong><p>{p.candidate.value}</p><small>{p.reason}</small></div>)}</>}
  <div className="two-columns"><div><h3>{t('text208')}</h3>{impact.affectedActions.length?impact.affectedActions.map(id=>{const a=baseline.actions.find(a=>a.id===id);return <p key={id}><strong>{id}</strong> · {a?.title} <Badge state={actionState(id,facts)}/> → <Badge state={actionState(id,previewFacts)}/></p>}):<p>{t('text209')}</p>}<h3>{t('text210')}</h3>{impact.recommendations.map(r=><p key={r}>{r}</p>)}{!impact.recommendations.length&&<p>{t('text211')}</p>}</div><div><h3>{t('text212')}</h3><details><summary>{t('text213')}{impact.unchanged.length}{t('text214')}</summary>{impact.unchanged.map(f=><p key={f.id}><strong>{f.id} · {f.subject}</strong>{t('text102')}{f.value}</p>)}</details><div className="notice"><LockKeyhole size={15}/>{t('text215')}</div></div></div><button className="button primary" onClick={save}><Save size={16}/>{t('text216')}</button></section>}
  {tab==='compare'&&<section className="card comparison"><div className="table-scroll"><table><thead><tr><th>{t('text217')}</th><th>{t('text218')}</th><th>{t('text219')}</th><th>{t('text004')}</th></tr></thead><tbody>{baseline.facts.filter(f=>f.informationState!=='historical').map(b=>{const f=displayFacts(facts).find(f=>f.id===b.id)!;return <tr className={f.eventId?'changed-row':''} key={b.id}><td><strong>{b.subject}</strong><small>{b.id} · {b.predicate}</small></td><td>{b.value}<Badge state={b.informationState}/></td><td>{f.value}<Badge state={f.informationState}/></td><td>{f.eventId?<><span className="mono">{f.eventId.slice(0,18)}{t('text220')}</span><p>{f.eventSource}</p><small>{t('text221')}</small></>:<><span>{t('text222')}</span><EvidenceLinks ids={b.locators.slice(0,1)} onEvidence={onEvidence}/></>}</td></tr>})}</tbody></table></div>{facts.filter(f=>f.id.startsWith("NEW-")).map(f=><div className="notice" key={f.id}><strong>{t('text223')}{f.subject}</strong><p>{t('text224')}{f.value}</p><Badge state={f.informationState}/><button className="text-button" onClick={()=>onEvidence(f.eventId!)}>{t('text225')}</button></div>)}</section>}
  {tab==='journal'&&<><div className="journal-toolbar"><button className="button secondary" onClick={exportJournal}><Download size={16}/>{t('text226')}</button><label className="button secondary upload-button"><Upload size={16}/>{t('text227')}<input type="file" accept="application/json,.json" onChange={e=>{void importJournal(e.target.files?.[0]);e.target.value='';}}/></label></div><p className="muted">{t('text228')}</p>{events.length===0?<div className="card empty-state"><LockKeyhole size={36}/><h2>{t('text229')}</h2><p>{t('text230')}</p></div>:events.map((e,i)=>{const currentBefore=deriveCurrent(events.slice(0,i));const result=analyzeEvent(currentBefore,e);return <article className="card journal-entry" key={e.id}><span className="mono">{e.id}</span><h2>{e.source}</h2><p>{e.author}{t('text231')}{e.occurredAt}{t('text232')}{e.receivedAt}</p><pre>{e.text}</pre><p><strong>{result.changed.length}{t('text233')}{result.newFacts.length}{t('text234')}</strong> · {result.pending.length}{t('text235')}{result.unchanged.length}{t('text236')}</p>{result.newFacts.map(f=><p key={f.id}><strong>{t('text237')}{f.subject}</strong> · {f.value} <Badge state={f.informationState}/></p>)}{result.changed.map(x=><p key={x.before.id}><strong>{x.before.subject}</strong>{t('text102')}{x.before.value} → {x.after.value} <Badge state={x.after.informationState}/></p>)}{result.pending.map((p,i)=><p key={i}><Badge state={p.candidate.state}/> {p.candidate.value} · {p.reason}</p>)}</article>})}</>}
  </>;
}
