'use client';
import {useTranslations,useLocale} from 'next-intl';
import {useProject} from '@/lib/project-context';
import { useState } from 'react';
import { ArrowDown, ArrowRight, History, ListFilter, CheckCheck } from 'lucide-react';
import {type Question} from '@/lib/data';
import {type DerivedFact,type ProjectEvent} from '@/lib/impact';
import { Badge, EvidenceLinks, SectionHeading, type EvidenceHandler } from './primitives';
export function TimelinePage({onEvidence}: {onEvidence:EvidenceHandler}) {
 const t=useTranslations('ui');const {timeline,dateLabel,labels}=useProject();const locale=useLocale();

  const [kind,setKind]=useState('all');const items=timeline.filter(e=>kind==='all'||e.eventType===kind);
  return <><SectionHeading eyebrow={t('text051')} title={t('text052')} description={t('text053')}><label className="filter"><ListFilter size={16}/><select aria-label={t('text054')} value={kind} onChange={e=>setKind(e.target.value)}><option value="all">{t('text055')}</option>{[...new Set(timeline.map(e=>e.eventType))].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label></SectionHeading><div className="timeline">{items.map(e=><article className={`timeline-event event-${e.eventType}`} id={e.id} key={e.id}><div className="timeline-date"><strong>{dateLabel(e.date)}</strong><span>{e.id}</span>{e.date.includes('T')&&<small>{new Date(e.date).toLocaleTimeString(locale==='en'?'en-CA':'fr-CA',{timeZone:'America/Montreal',hour:'2-digit',minute:'2-digit'})}{t('text057')}</small>}</div><span className="timeline-dot"/><div className="card"><Badge state={e.eventType}/><h2>{e.title}</h2><p>{e.description}</p><details><summary>{t('text058')}</summary><p>{t('text059')}{e.relatedFactIds.join(t('text060'))||t('text061')}{e.relatedActionIds.length>0&&t('text062',{v0:e.relatedActionIds.join(' · ')})}</p>{e.people.length>0&&<p>{e.people.join(t('text060'))}</p>}<EvidenceLinks ids={e.evidence} onEvidence={onEvidence}/></details></div></article>)}</div></>;
}
export function NewEventsTimeline({events,onEvidence}: {events:ProjectEvent[];onEvidence:EvidenceHandler}) {
 const t=useTranslations('ui');const {dateLabel}=useProject();

  if(!events.length)return null;
  return <section className="new-events-timeline"><SectionHeading eyebrow={t('text063')} title={t('text064')} description={t('text065')}/><div className="timeline">{events.map(event=><article className="timeline-event" key={event.id}><div className="timeline-date"><strong>{dateLabel(event.occurredAt)}</strong><small>{t('text066')}</small></div><span className="timeline-dot"/><div className="card"><span className="mono">{event.id}</span><h2>{event.source}</h2><p>{event.author}</p><pre>{event.text}</pre><div className="button-row">{event.candidates.map((c,i)=><Badge key={i} state={c.state}/>)}</div><button className="text-button" onClick={()=>onEvidence(event.id)}>{t('text067')}</button></div></article>)}</div></section>;
}
export function DecisionsPage({onEvidence}: {onEvidence:EvidenceHandler}) {
 const t=useTranslations('ui');const {decisions}=useProject();const n=useTranslations('nav');

  return <><SectionHeading eyebrow={t('text068')} title={t('text069')} description={t('text070')}/><p className="snapshot-caption">{n('baselineHistory')}</p><div className="decision-grid">{decisions.map(d=><article className="card decision-card" id={d.id} key={d.id}><div className="panel-heading"><span className="mono">{d.id} · {d.topic}</span><Badge state={d.approvedAt?'approved':'proposed'}/></div><h2>{d.title}</h2><p>{d.rationale}</p><div className="decision-dna">{d.phases.map((phase,i)=><div key={i}><span className="dna-number">{i+1}</span><div><span className="eyebrow">{phase.label}</span><p>{phase.text}</p><EvidenceLinks ids={phase.evidence} onEvidence={onEvidence}/></div>{i<d.phases.length-1&&<ArrowDown className="dna-arrow" size={14}/>}</div>)}</div><div className="notice"><strong>{t('text071')}</strong>{d.validationState}</div><small>{t('text072')}{d.affectedFacts.join(t('text060'))}{d.affectedActions.length>0&&t('text073',{v0:d.affectedActions.join(' · ')})}</small></article>)}</div></>;
}
export function ActionsPage({facts,onEvidence}: {facts:DerivedFact[];onEvidence:EvidenceHandler}) {
 const t=useTranslations('ui');const {baseline,actionState}=useProject();

  const [filter,setFilter]=useState('all');const rows=baseline.actions.filter(a=>filter==='all'||(filter==='documented'?a.recommendationOrCommitment==='documented_commitment':a.recommendationOrCommitment==='team_recommendation'));
  return <><SectionHeading eyebrow={t('text074')} title={t('text075')} description={t('text076')}/><div className="segmented" aria-label={t('text077')}>{[['all',t('text139')],['documented',t('text078')],['recommended',t('text210')]].map(([id,label])=><button aria-pressed={filter===id} className={filter===id?'active':''} key={id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="action-grid">{rows.map(a=><article className="card action-card" id={a.id} key={a.id}><div className="panel-heading"><span className={`commitment ${a.recommendationOrCommitment==='team_recommendation'?'recommendation':''}`}>{a.recommendationOrCommitment==='team_recommendation'?t('text080'):t('text081')}</span><span className="mono">{a.id}</span></div><h2>{a.title}</h2><p>{a.description}</p><Badge state={actionState(a.id,facts)}/><dl className="action-details"><dt>{t('text082')}</dt><dd>{a.owner}<small>{a.ownerType==='confirmed'?t('text083'):t('text084')}</small></dd><dt>{t('text085')}</dt><dd>{a.dueDate??t('text086')}<small>{a.deadlineConstraint}</small></dd><dt>{t('text087')}</dt><dd>{baseline.conditions.find(c=>c.id===a.relatedGoLiveCondition)?.title??t('text088')}</dd></dl>{facts.filter(f=>f.eventId&&a.relatedFactIds.includes(f.id)).map(f=><button className="text-button" key={f.id} onClick={()=>onEvidence(f.eventId!)}>{t('text103')}</button>)}<EvidenceLinks ids={a.sourceEvidence} onEvidence={onEvidence}/></article>)}</div></>;
}
export function ContradictionsPage({onEvidence,facts}: {onEvidence:EvidenceHandler;facts:DerivedFact[]}) {
 const t=useTranslations('ui');const {baseline,contradictions}=useProject();const n=useTranslations('nav');

  return <><SectionHeading eyebrow={t('text089')} title={t('text090')} description={t('text091')}/><p className="snapshot-caption">{n('baselineHistory')}</p><div className="conflict-list">{contradictions.map(c=><article className="card conflict-card" id={c.id} key={c.id}><div className="panel-heading"><span className="mono">{c.id}</span><span className="resolved"><CheckCheck size={15}/>{t('text092')}</span></div><h2>{c.topic}</h2><div className="claims"><div><span className="eyebrow">{t('text093')}</span><p>{c.factA}</p></div><span className="versus">{t('text094')}</span><div><span className="eyebrow">{t('text095')}</span><p>{c.factB}</p></div></div><div className="resolution"><History size={20}/><div><strong>{t('text096')}</strong><p>{c.resolution}</p><small>{c.resolutionBasis}</small></div></div><div className="current-truth"><span>{t('text097')}</span><strong>{baseline.facts.find(f=>f.id===c.currentFactId)?.value}</strong><ArrowRight size={16}/><span className="mono">{c.currentFactId}</span></div>{facts.filter(f=>f.id===c.currentFactId&&f.eventId).map(f=><div className="notice" key={f.id}><strong>{n('currentEvent')}</strong><p>{f.value}</p><Badge state={f.informationState}/><button className="text-button" onClick={()=>onEvidence(f.eventId!)}>{t('text103')}</button></div>)}<EvidenceLinks ids={c.evidence} onEvidence={onEvidence}/></article>)}</div></>;
}
export function QuestionCard({question,onEvidence,facts}: {question:Question;onEvidence:EvidenceHandler;facts?:DerivedFact[]}) {
 const t=useTranslations('ui');const n=useTranslations('nav');

  const changed=facts?.filter(f=>f.eventId&&question.relatedFactIds.includes(f.id))??[];
  return <article className="card question-card" id={question.id}><div className="question-number">{question.isOfficial===false?'+':Number(question.id.slice(1))}</div><div className="question-body"><div className="panel-heading"><span className="eyebrow">{question.isOfficial===false?n('derived'):t('text098')}</span><Badge state={question.status}/></div><h2>{question.question}</h2><p className="answer">{question.answer}</p><p>{question.nuance}</p><div className="confidence"><CheckCheck size={16}/><strong>{question.isOfficial===false?(question.evidence.length?n('moderate'):t('text086')):t('text099')}</strong><span>{question.isOfficial===false?n('review'):t('text100')}</span></div>{changed.length>0&&<div className="notice"><strong>{t('text101')}</strong>{changed.map(f=><p key={f.id}>{f.subject}{t('text102')}{f.value} <Badge state={f.informationState}/> · {f.eventSource} <button className="text-button" onClick={()=>onEvidence(f.eventId!)}>{t('text103')}</button></p>)}<small>{t('text104')}</small></div>}<details><summary>{t('text105')}</summary><p>{question.uncertainty}</p><p>{question.relatedFactIds.join(t('text060'))}</p><p>{question.crossSourceConfirmation}</p></details><EvidenceLinks ids={question.evidence} onEvidence={onEvidence}/></div></article>;
}
export function QuestionsPage({onEvidence,facts}: {onEvidence:EvidenceHandler;facts:DerivedFact[]}) {
 const t=useTranslations('ui');const n=useTranslations('nav');const {baseline}=useProject();
 const official=baseline.questions.filter(q=>q.isOfficial!==false);const custom=baseline.questions.filter(q=>q.isOfficial===false);
 return <><SectionHeading eyebrow={t('text106')} title={t('text107')} description={t('text108')}/>
 <nav className="question-jump" aria-label={t('text109')}>{official.map(q=><a key={q.id} href={`#${q.id}`} aria-label={q.question}>{Number(q.id.slice(1))}</a>)}{custom.map((q,i)=><a key={q.id} href={`#${q.id}`} aria-label={q.question}>{n('custom')} {i+1}</a>)}</nav>
 <div className="questions-list">{official.map(q=><QuestionCard key={q.id} question={q} onEvidence={onEvidence} facts={facts}/>)}{custom.length>0&&<><h2 className="team-questions-heading">{n('teamQuestions')}</h2>{custom.map(q=><QuestionCard key={q.id} question={q} onEvidence={onEvidence} facts={facts}/>)}</>}</div></>;
}
