'use client';
import {useEffect,useRef,useState} from 'react';
import {useSearchParams,usePathname} from 'next/navigation';
import {useLocale,useTranslations} from 'next-intl';
import {Search,X,ArrowRight} from 'lucide-react';
import type {SearchResult} from '@/lib/repositories/search';
import {useProject} from '@/lib/project-context';
const kinds=['all','questions','evidence','facts','decisions','actions','timeline','contradictions','people'];
export function SearchExperience({onOpen,initialQuery='',onClose}:{onOpen:(result:SearchResult)=>void;initialQuery?:string;onClose?:()=>void}){
 const params=useSearchParams();const pathname=usePathname();const t=useTranslations('search');const locale=useLocale();const {labels}=useProject();const [query,setQuery]=useState(params.get('q')??initialQuery);const [kind,setKind]=useState(params.get('kind')??'all');const [state,setState]=useState(params.get('state')??'all');const [results,setResults]=useState<SearchResult[]>([]);const [counts,setCounts]=useState<Record<string,number>>({});const [selected,setSelected]=useState(0);const [loading,setLoading]=useState(false);const [error,setError]=useState(false);const input=useRef<HTMLInputElement>(null);const list=useRef<HTMLDivElement>(null);
 useEffect(()=>{input.current?.focus();},[]);
 useEffect(()=>{if(!onClose){const next=new URLSearchParams(window.location.search);for(const [key,value]of Object.entries({q:query,kind,state})){if(value&&value!=='all')next.set(key,value);else next.delete(key);}const text=next.toString();window.history.replaceState(null,'',pathname+(text?'?'+text:''));}},[query,kind,state,pathname,onClose]);
 useEffect(()=>{const abort=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setError(false);try{const response=await fetch('/api/search?'+new URLSearchParams({q:query,locale,kind,state}),{signal:abort.signal});if(!response.ok)throw new Error();const data=await response.json();setResults(data.results);setCounts(data.counts);setSelected(0);}catch{if(!abort.signal.aborted)setError(true);}finally{if(!abort.signal.aborted)setLoading(false);}},180);return ()=>{clearTimeout(timer);abort.abort();};},[query,locale,kind,state]);
 useEffect(()=>{list.current?.querySelector<HTMLElement>(`[data-index="${selected}"]`)?.scrollIntoView({block:'nearest'});},[selected]);
 const highlight=(text:string)=>{if(!query.trim())return text;const escaped=query.trim().split(/\s+/).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));const pattern=new RegExp(`(${escaped.join('|')})`,'ig');return text.split(pattern).map((part,i)=>i%2?<mark key={i}>{part}</mark>:part);};
 return <section className="search-experience" onKeyDown={e=>{if(e.key==='Escape')onClose?.();if((e.key==='ArrowDown'||e.key==='ArrowUp')&&(e.target===input.current||(e.target as HTMLElement).getAttribute('role')==='option')){e.preventDefault();input.current?.focus();setSelected(s=>Math.max(0,Math.min(results.length-1,s+(e.key==='ArrowDown'?1:-1))));}if(e.key==='Enter'&&e.target===input.current&&results[selected]){e.preventDefault();onOpen(results[selected]);}}}><div className="search-heading"><h1>{t('title')}</h1>{onClose&&<button className="icon-button" aria-label={t('close')} onClick={onClose}><X/></button>}</div><label className="palette-input"><Search/><input ref={input} role="combobox" aria-label={t('title')} aria-autocomplete="list" aria-expanded={!!query.trim()} aria-controls="search-results" aria-activedescendant={results[selected]?'search-result-'+selected:undefined} placeholder={t('placeholder')} value={query} maxLength={1000} onChange={e=>setQuery(e.target.value)}/></label><div className="search-filters" aria-label={t('title')}>{kinds.map(k=><button key={k} className={kind===k?'active':''} aria-pressed={kind===k} onClick={()=>{setKind(k);input.current?.focus();}}>{t(k)}{counts[k]!==undefined&&<span>{counts[k]}</span>}</button>)}</div><label className="search-state">{t('state')}<select value={state} onChange={e=>setState(e.target.value)}><option value="all">{t('all')}</option>{['current','historical','approved','pending','uncertain','validated'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>
 {!query.trim()?<div className="search-shortcuts"><h2>{t('shortcuts')}</h2>{['launch','conditions','INV-003','security','accessibility','budget','owner'].map(key=><button key={key} onClick={()=>setQuery(key==='INV-003'?key:t(key))}>{key==='INV-003'?key:t(key)}<ArrowRight size={16}/></button>)}</div>:<><p role="status" className="muted">{loading?t('loading'):error?t('error'):t('count',{count:counts[kind]??0})}</p><div ref={list} id="search-results" role="listbox" aria-label={t('title')} className="search-results">{results.map((r,i)=><button id={'search-result-'+i} data-index={i} role="option" aria-selected={selected===i} key={r.kind+r.id} className={`search-result ${selected===i?'selected':''}`} onMouseEnter={()=>setSelected(i)} onClick={()=>onOpen(r)}><span className="result-kind">{t(r.kind)} · {labels[r.state]??r.state} · {t('scope_'+(r.scope??'baseline'))}</span>{r.kind==='evidence'&&r.scope==='original'&&<small>{t('original')}</small>}<strong>{highlight(r.title)}</strong><span>{highlight(r.snippet)}</span><small>{t('openResult')}<ArrowRight size={14}/></small></button>)}{!loading&&!error&&!results.length&&<p>{t('empty')}</p>}</div></>}
 <p className="search-key-hint">{t('keys')}</p></section>;
}
export function SearchPalette({open,onClose,onOpen}:{open:boolean;onClose:()=>void;onOpen:(result:SearchResult)=>void}){const ref=useRef<HTMLDialogElement>(null);const t=useTranslations('search');useEffect(()=>{if(open&&!ref.current?.open)ref.current?.showModal();if(!open&&ref.current?.open)ref.current.close();},[open]);return <dialog ref={ref} className="search-dialog" aria-label={t('title')} onCancel={onClose} onClose={onClose}>{open&&<SearchExperience onClose={onClose} onOpen={r=>{onClose();onOpen(r);}}/>}</dialog>;}
