import {appRoutes} from '../navigation';
import type {Locale,SupportRole} from './types';
type Route={page:string;title:Record<Locale,string>;description:Record<Locale,string>;admin?:boolean};
const section=(page:string,fr:string,en:string,descriptionFr:string,descriptionEn:string,admin=false):Route=>({page,title:{fr,en},description:{fr:descriptionFr,en:descriptionEn},admin});
export const supportRoutes={
 overview:section('home','Vue d’ensemble','Overview','Six indicateurs factuels, chronologie et documents.','Six factual indicators, timeline and documents.'),
 projectStatus:section('overview','État détaillé','Detailed project status','Conditions de lancement indépendantes, date approuvée et preuve.','Independent launch conditions, approved date and evidence.'),
 timeline:section('timeline','Chronologie','Timeline','Historique original et événements reçus; les dates et la provenance restent visibles.','Original history and received events, with dates and provenance.'),
 questions:section('questions','Q01–Q10','Q01–Q10','Réponses officielles vérifiées au baseline, nuances et citations. Les changements courants sont signalés séparément.','Verified official baseline answers, nuances and citations; current changes are shown separately.'),
 decisions:section('decisions','Décisions','Decisions','Proposition, approbation et mise en œuvre distinctes; historique conservé.','Proposal, approval and implementation stay distinct; history is preserved.'),
 tasks:section('actions','Tâches','Tasks','Engagements documentés et recommandations distincts; responsables et échéances.','Documented commitments and recommendations, owners and deadlines.'),
 risks:section('contradictions','Risques','Risks','Contradictions historiques et preuves; les conditions ouvertes sont dans État détaillé et Tâches. Ne pas qualifier toutes les contradictions de risques actuels non résolus.','Historical contradictions and evidence; open conditions are in Detailed project status and Tasks. Not all contradictions are current unresolved risks.'),
 evidence:section('evidence','Preuves traçables','Traceable Evidence','Rechercher/filtrer les originaux; source et repère précis visibles. Métadonnées avancées sous Voir le détail.','Search/filter originals; source and precise locator visible, advanced metadata under View details.'),
 documents:section('documents','Documents','Documents','Bibliothèque filtrable des documents originaux, avec liens vers les fichiers et leurs preuves détaillées.','Filterable original document library, with links to files and their detailed evidence.'),
 search:section('search','Recherche','Search','Recherche interactive bilingue par mots-clés, types et états. Ctrl/Cmd K ouvre la palette. Le champ principal dirige vers Ask NOVA.','Bilingual interactive keyword/type/state search. Ctrl/Cmd K opens the palette. The main question field opens Ask NOVA.'),
 impact:section('impact','Mode Impact','Impact Mode','Analyser un événement, déclarer source/auteur, confirmer les candidats puis enregistrer explicitement. Comparer Baseline/Actuel. Proposition ≠ approbation; livraison ≠ validation. Chaque condition se ferme indépendamment.','Analyze an event, declare source/author, review candidates, then explicitly save. Compare Baseline/Current. Proposal is not approval; delivery is not validation. Each condition closes independently.'),
 askNova:section('ask','Ask NOVA','Ask NOVA','Questions factuelles du projet, réponses vérifiées et incertitude explicite. Support aide surtout à naviguer.','Factual project questions, verified answers and explicit uncertainty. Support primarily helps navigation.'),
 adminQuestions:section('admin','Question Bank (Admin)','Question Bank (Admin)','ADMIN connecté: créer/modifier/désactiver des questions personnalisées bilingues, citations et audit. Q01–Q10 protégées.','Signed-in ADMIN: create/edit/deactivate bilingual custom questions with citations/audit. Q01–Q10 protected.',true),
 adminUsers:section('users','Utilisateurs','User Management','ADMIN connecté: rechercher/activer/désactiver des comptes. Rôles en lecture seule, pas de suppression, protection du propre compte/dernier admin.','Signed-in ADMIN: search/activate/deactivate accounts. Roles read-only, no deletion, self/last-admin protection.',true),
 login:section('login','Connexion','Login','Connexion par courriel/mot de passe. Compte désactivé refusé. Déconnexion via le menu du compte.','Email/password login; disabled accounts rejected. Logout through account menu.'),
 register:section('register','Créer un compte','Register','Nom, courriel unique, mot de passe de 10 caractères minimum et confirmation. Rôle USER, connexion après inscription.','Name, unique email, password of at least 10 characters and confirmation. Initial USER role, signed in after registering.'),
 team:section('team','Équipe','Team','Responsables documentés du projet; distincts des comptes de connexion.','Documented project people, distinct from login accounts.'),
 brief:section('brief','Brief de reprise','Takeover brief','Brief A4 imprimable et export texte.','Printable A4 brief and text export.'),
} satisfies Record<string,Route>;
export type RouteKey=keyof typeof supportRoutes;
export function accessibleRoutes(role:SupportRole){return Object.entries(supportRoutes).filter(([,r])=>!r.admin||role==='ADMIN');}
export function resolveRoute(key:string,locale:Locale,role:SupportRole){if(!Object.hasOwn(supportRoutes,key))return null;const route=supportRoutes[key as RouteKey];if(route.admin&&role!=='ADMIN')return null;return {label:(locale==='fr'?'Ouvrir ':'Open ')+route.title[locale],href:`/${locale}/${appRoutes[route.page]}`};}
export function preserveView(href:string,view:'baseline'|'current'){if(view!=='baseline'||/\/(?:login|register|admin)(?:\/|$)/.test(href))return href;const [path,anchor]=href.split('#');return path+(path.includes('?')?'&':'?')+'view=baseline'+(anchor?'#'+anchor:'');}
export function normalizeCurrentPath(value:unknown,locale:Locale){if(typeof value!=='string'||value.length>300)return `/${locale}`;const path=value.split(/[?#]/)[0].replace(/\/$/,'');return accessibleRoutes('ADMIN').some(([,r])=>path===`/${locale}/${appRoutes[r.page]}`.replace(/\/$/,''))?path:`/${locale}`;}
